= Directory Package

== Overview

The directory package is illustrated below. It provides a simple abstraction of a versioned folder structure. The `VERSIONED_FOLDER` class is the binding of `VERSIONED_OBJECT<T>` to the class `FOLDER`, i.e. it is a `VERSIONED_OBJECT<FOLDER>`. This means that each of its versions is a Folder structure rather than a single Folder. It provides a means of versioning `FOLDER` structures over time, which is useful in the EHR, Demographics service or anywhere else where Folders are used to group things. A `FOLDER` instance contains more `FOLDERs` and/or items, which are references to other (usually versioned) objects. A `FOLDER` structure is therefore like a directory containing references to objects. Since they are references, multiple references to the same object are possible, allowing the structure to be used to mutiply classify other objects. If it is used with `VERSIONED_COMPOSITIONs` for example, the folders might be used to represent episodes and at the same time problem groups.

[.text-center]
.common.directory Package
image::{uml_export_dir}/diagrams/RM-common.directory.svg[id=directory_package, align="center"]

`FOLDER` structures inside the `VERSIONED_FOLDER` are archetypable structures, and `FOLDER` archetypes can be created in the same fashion as say `SECTION` archetypes for the EHR.

=== Paths
Directory paths are built using the name attribute values inherited from `LOCATABLE` into each `FOLDER` object. In real data, these will usually be derived from the value of the `_archetype_node_id_` attribute, plus a uniqueness modifier if required. Example paths (e.g. within the EHR):

----
    /folders[hospital episodes]/items[1]
    /folders[patient entered data]/folders[diabetes monitoring]
    /folders[homeopathy contacts]
----

Uniqueness modifiers are appended in brackets, and are only needed to differentiate folders at the same node that would otherwise have the same names, e.g.

----
    [hospital episodes]
    [hospital episodes(car accident Aug 1998)]
----

== Class Descriptions

include::{uml_export_dir}/classes/versioned_folder.adoc[]

include::{uml_export_dir}/classes/folder.adoc[]
