= Overview

The openEHR Common Information Model defines various abstract concepts and design patterns used in higher level openEHR models.

The `archetyped` package is informed by a number of design principles, centred on the concept of 'two-level' modelling. These principles are described in detail in cite:[Beale2000]. The `generic` package contains classes forming 'analysis patterns' which are generic across the domain, mostly to do with referencing demographic entities from within other data including `PARTICIPATION`, `PARTY_PROXY`, `ATTESTATION` and so on.

The `directory` package provides a simple reusable abstraction of a versioned folder structure. 

The `change_control` package defines the generalised semantics of changes to a logical repository, such as an EHR, over time. Each item in such a repository is version-controlled to allow the repository as a whole to be properly versioned in time. The semantics described are in response to medicolegal requirements defined in cite:[GEHR1995], and in the ISO Technical Specification {iso_18308}[ISO 18308^]. Both of these requirements specifications mention specifically the version control of the health record.

The `resource` package defines semantics of an online authored resource, such as a document, and supports multiple language translations, descriptive meta-data and revision history.
