= Preface

== Purpose

This document describes the openEHR EHR Information Model, which is a model of an interoperable EHR in the ISO RM/ODP information viewpoint. This model defines a logical EHR information architecture rather than just an architecture for communication of EHR extracts or documents between EHR systems. The openEHR definition of the EHR Extract is given in the openEHR EHR_EXTRACT Information Model.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.
* Health data managers.

== Related Documents

Prerequisite documents for reading this document include:

* The openEHR Architecture Overview (<<openehr_overview>>);

Related documents include:

* The openEHR Support Information Model (<<openehr_rm_support>>).
* The openEHR Data Types Information Model (<<openehr_rm_data_types>>).
* The openEHR Data Structures Information Model (<<openehr_rm_data_structures>>).
* The openEHR Common Information Model (<<openehr_rm_common>>).

== Status

This specification is in the Stable state. The development version of this document can be found at http://www.openehr.org/releases/trunk/architecture/rm/ehr_im.pdf.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Conformance

Conformance of a data or software artifact to an openEHR Reference Model specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal, automated derivations from the Reference Model, ITS conformance indicates RM conformance.

