= Preface

== Purpose

This document describes the architecture of the openEHR Demographic Information Model. The
semantics are drawn from previous work in GEHR, existing models in CEN 13606 and the HL7v3
RIM, and other work done in Australia.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The openEHR Architecture Overview (<<openehr_overview>>);

Other documents describing related models, include:

* The openEHR Support Information Model (<<openehr_rm_support>>).
* The openEHR Data Types Information Model (<<openehr_rm_data_types>>).

== Status

This specification is in the Stable state. The development version of this document can be found at http://www.openehr.org/releases/RM/latest/demographic.html.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Conformance

Conformance of a data or software artifact to an openEHR Reference Model specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal, automated derivations from the Reference Model, ITS conformance indicates RM conformance.

