= Preface

== Purpose

This document describes the architecture of the openEHR Demographic Information Model. The semantics are drawn from previous work in {openehr_gehr}[GEHR^], existing models in CEN 13606 and the HL7v3 RIM, and other work done in Australia.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].

Other documents describing related models, include:

* The {openehr_rm_support}[openEHR Support Information Model^];
* The {openehr_rm_data_types}[openEHR Data Types Information Model^].

== Status

This specification is in the Stable state. The development version of this document can be found at {openehr_rm_latest_demographic}[{openehr_rm_latest_demographic}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

