= Assumed Types

== Overview

This section describes types assumed by all openEHR models. The set of types chosen here is based
on a common set from various published sources, including:

* ISO 11404 (2003 revision) general purpose data types;
* ISO 8601 (2004) date/time specification;
* Well-known interoperability formalisms, including OMG IDL, W3C XML-schema;
* Well-known object-oriented programming languages, including Java, C#, C++ and Eiffel.

The intention in openEHR is twofold. Firstly, to ensure that openEHR software based on the models
integrates as easily as possible with existing implementation technologies, and secondly, to make the
minimum possible assumptions about types found in implementation formalisms, while making sufficient
assumptions to both enable openEHR models to be conveniently specified. The ISO 11404
(2003) standard contains basic semantics of "general purpose data types" (GPDs) for information
technology, and is used here as a normative basis for describing assumptions about types. The operations
and properties described here are compatible with those used in ISO 11404, but not always the
same, as 11404 does not use object-oriented functions. For example, the notional function `has (x:T)`
(test for presence of a value in a set) defined on the type `Set<T>` below is not defined on the ISO
11404 Set type; instead, the function `IsIn(x: T; s: Set<T>)` is defined. However, in object-oriented
formalisms, the function IsIn defined on a Set type would usually mean 'subset of'. In the
interests of clarity for developers, an object-oriented style of functions and properties has been used
here.

ISO8601:2004 is used as the definitional basis for assumed date/time types, since it is commonly
used around the world, and is also the basis for the date/time types in W3C XML-schema. See section
<<Date/Time Types>> below for details of dates and times.

Two groups of assumed types are identified: primitive types, which are those built in to a formalism's
type system, and library types, which are assumed to be available in a (class) library defined in the
formalism. Thus, the type Boolean is always assumed to exist in a formalism, while the type
Array<T> is assumed to be available in a library. For practical purposes, these two categories do not
matter that much - whether String is really a library class (the usual case) or an inbuilt type doesn't
make much difference to the programmer. They are shown separately here mainly as an explanatory
convenience.

The assumptions that openEHR makes about existing types are documented below in terms of interface
definitions. Each of these definitions contains _only the assumptions required for the given type to be used in the openEHR Reference Model_ - *it is not by any means a complete interface definition*.
The name and semantics of any function used here for an assumed type *might not be identical* to
those found in some implementation technologies. Any mapping required should be stated in the relevant
implementation technology specification (ITS). To give a concrete example, where the
assumed `Set<T>` type defined below has an operation `has (item: T): Boolean` which is used throughout
the openEHR specifications, Java has the method contains() on its `Set<T>` class. In a Java implementation,
the `contains ()` method should then be used throughout the openEHR classes as expressed
in Java, in place of the `has ()` method.

== Inbuilt Primitive Types

The following types consititute the minimum set of primitive types assumed by openEHR of an
implementation formalism.

[cols="1,3,1", options="header"]
|===
|Type name +
 in openEHR 
|Description
|ISO 11404 +
 Type

|`Octet`    |represents a type whose value is an 8-bit value.                                           |`Octet`
|`Character`|represents a type whose value is a member of an 8-bit character-set (ISO: "repertoire").  |`Character`
|`Boolean`  |represents logical True/False values; usually physically represented as an integer, but need not be |`Boolean`
|`Integer`  |represents 32-bit integers                                                                 |`Integer`
|`Integer64`|represents 64-bit integers                                                                 |`Integer64`
|`Real`     |represents 32-bit real numbers in any interoperable representation, including single-width IEEE floating point |`Real`
|`Double`   |type which represents 64-bit real numbers, in any interoperable representation including double-precision IEEE floating point. |`Real`

|===

The figure below illustrates the built-in primitive types. Simple inheritance relationships are shown which
facilitate the type descriptions below. A class "Any" is used to stand for the usual top-level class in all
object-oriented type systems, typically called something like "Any" or "Object". Inheritance from or
subsitutability for an Any class is not assumed in openEHR (hence the dotted lines in the UML). It is
used here to enable basic operations like '=' to be described once for the type Any, rather than in
every subtype. The type Ordered_numeric is on the other hand assumed for purposes of specification
in the openEHR data_types.quantity package, and is intended to be mapped to an equivalent
type in a real type system (e.g. in Java, java.lang.Number). Here it is assumed that the
operations defined on Ordered_numeric are available on the types Integer, Real and Double in
implementation type systems, where relevant. Data-oriented implementation type systems such as
XML-schema do not have such operations.

[.text-center]
.Primitive Types Assumed by openEHR
image::{uml_export_dir}/diagrams/BASE-base_types.assumed_types.svg[id=base_assumed_types, align="center"]

include::{uml_export_dir}/classes/any.adoc[]

include::{uml_export_dir}/classes/numeric.adoc[]

include::{uml_export_dir}/classes/ordered.adoc[]

include::{uml_export_dir}/classes/ordered_numeric.adoc[]

include::{uml_export_dir}/classes/boolean.adoc[]

include::{uml_export_dir}/classes/integer.adoc[]

include::{uml_export_dir}/classes/integer64.adoc[]

include::{uml_export_dir}/classes/real.adoc[]

== Assumed Library Types

The types described in this section are also assumed to be fairly standard in implementation technologies
by openEHR, but usually come from type libraries rather than being built into the type system of
implementation formalisms.

[cols="1,3,1", options="header"]
|===
|Type name +
 in openEHR 
|Description
|ISO 11404 +
 Type

|`String`               |represents unicode-enabled strings                         |Character-String/Sequence
|`Array<T>`             |physical container of items indexed by number              |Array
|`List<T>`              |container of items, implied order, non-unique membership   |Sequence
|`Set<T>`               |container of items, no order, unique membership            |Set
|`Hash<T,U:Comparable>` |a table of values of any type T, keyed by values of any basic comparable type U, typically String or Integer, but may be more complex types, e.g. a coded term type. | Table
|`Interval<T>`          |Intervals with open or closed upper and lower bounds.      |-
|===

The following UML diagram illustrates the assumed library types. As with the assumed primitive types, inheritance and
abstract classes are used for convenience of the definitions below, but are not formally assumed in
openEHR.

[.text-center]
.Library Types Assumed by openEHR
image::{uml_export_dir}/diagrams/BASE-base_types.structure.svg[id=base_structure_types, align="center"]

include::{uml_export_dir}/classes/string.adoc[]

==== Unicode

It is assumed in the openEHR specifications that Unicode is supported by the type String. Unicode
is needed for all Asian, Arabic and other script languages, for both data values (particularly plain text
and coded text) and for many predefined string attributes of the classes in the openEHR Reference
Model. It encompasses all existing character sets. In openEHR, UTF-8 encoding is assumed.

include::{uml_export_dir}/classes/aggregate.adoc[]

include::{uml_export_dir}/classes/list.adoc[]

include::{uml_export_dir}/classes/set.adoc[]

include::{uml_export_dir}/classes/array.adoc[]

include::{uml_export_dir}/classes/hash.adoc[]

include::{uml_export_dir}/classes/interval.adoc[]

== Date/Time Types

Although the ISO 11404 (2003) standard defines a date-and-time type generator (section 8.1.6), and a
timeinterval type (section 10.1.6), a more widely used specification of date/times is given by ISO
8601:2004, which is used as the normative basis for both string literal representation and properties
used within openEHR. The types are shown in the UML diagram below.

[.text-center]
.Date/Time types assumed by openEHR
image::{uml_export_dir}/diagrams/BASE-base_types.time.svg[id=base_time_types, align="center"]

ISO 8601 semantics not used in openEHR include:

* "expanded" dates, which have year numbers of greater than 4 digits, and may be negative; in
openEHR, only 4-digit year numbers are assumed;
* the YYYY-WW-DD method of expressing dates (since this is imprecise and difficult to
compute with due to variable week starting dates, and not required in health);
* partial date/times with fractional minutes or hours, e.g. hh,hhh or mm,mm; in openEHR,
only fractional seconds are supported;
* the interval syntax. Intervals of date/times are supported in openEHR, but their syntax form
is defined by ADL, and is standardised across all comparable types, not just dates and times.

Deviations from the published standard include the following:

* durations are supposed to take the form of PnnW or PnnYnnMnnDTnnHnnMnnS, but in
openEHR, the W (week) designator can be used in combination with the other designators,
since it is very common to state durations of pregnancy as some combination of weeks and
days.
* partial variants of ISO8601_DATE_TIME can include missing hours, days and months,
whereas ISO 8601:2004 (section 4.3.3 c) only allows missing seconds and minutes. The reasons
for this deviation are:
** the same deviation is used in HL7v2 and HL7v3 TS (timestamp) type, i.e. there are
data in existing clinical systems matching this specification;
** in a typed object model, this deviation is more sensible anyway; the ISO 8601 rule
is most likely a limitation of the purely syntactic means of expression. In real
systems where a timestamp/date-time is specified in a screen form, it makes sense
to allow it to be as partial as possible, rather than artifically restricted to only
missing seconds and minutes.
* the time 24:00:00 (or 240000) is not allowed anywhere, whereas in ISO8601:2004 it
appears to be legal at least for times. This deviation is also appears to be used in HL7v2 and
HL7v3 (where midnight is defined as the time 00:00:00), and is preferable to the documented
standard, since a date/time with time of 24:00:00 is really the next day, i.e. the date
part is then incorrect.

The following class definitions provide an object-oriented expression of the semantics of the subset
of ISO 8601:2004 used by openEHR.

See http://www.cl.cam.ac.uk/~mgk25/iso-time.html and the official ISO standard for ISO
8601 details. Note that in the date, time and date_time formats shown below, 'Z' and 'T' are literals.
In the duration class shown below, 'P', 'Y', 'M', 'W', 'D', 'H', 'S' and 'T' are literals.

include::{uml_export_dir}/classes/time_definitions.adoc[]

include::{uml_export_dir}/classes/iso8601_type.adoc[]

include::{uml_export_dir}/classes/iso8601_date.adoc[]

include::{uml_export_dir}/classes/iso8601_time.adoc[]

include::{uml_export_dir}/classes/iso8601_date_time.adoc[]

include::{uml_export_dir}/classes/iso8601_duration.adoc[]

include::{uml_export_dir}/classes/iso8601_timezone.adoc[]
