=== ACTIVITY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*ACTIVITY*

h|*Description*
2+a|Defines a single activity within an Instruction, such as a medication administration.

h|*Inherit*
2+|`LOCATABLE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*timing*: `DV_PARSABLE`
a|Timing of the activity, in the form of a parsable string. If used, the preferred syntax is ISO8601 'R' format, but other formats may be used including HL7 GTS.

May be omitted if:

* timing is represented structurally in the `_description_` attribute (e.g. via archetyped elements), or
* unavailable, e.g. imported legacy data; in such cases, the `INSTRUCTION._narrative_` should carry text that indicates the timing of its `_activities_`.

h|*0..1*
|*action_archetype_id*: `String`
a|Perl-compliant regular expression pattern, enclosed in  '//' delimiters, indicating the valid identifiers of archetypes for Actions corresponding to this Activity specification.

Defaults to  `/.*/`, meaning any archetype.

h|*1..1*
|*description*: `ITEM_STRUCTURE`
a|Description of the activity, in the form of an archetyped structure.

h|*Invariants*
2+a|*_Action_archteype_id_valid_*: `not action_archetype_ids.is_empty`
|===
