=== ACTOR Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__ACTOR (abstract)__*

h|*Description*
2+a|Ancestor of all real-world types, including people and organisations. An actor is any real-world entity capable of taking on a role.

h|*Inherit*
2+|`<<_party_class,PARTY>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*languages*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/RM/{rm_release}/data_types.html#_dv_text_class[DV_TEXT^]>`
a|Languages which can be used to communicate with this actor, in preferred order of use (if known, else order irrelevant).

h|*1..1*
|*roles*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/RM/{rm_release}/support.html#_party_ref_class[PARTY_REF^]>`
a|Identifiers of the Version container for each Role played by this party.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*has_legal_identity* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if one there is an identity with purpose  legal identity.

h|*Invariants*
2+a|__Legal_identity_exists__: `has_legal_identity`
|===
