=== ARCHETYPED Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*ARCHETYPED*

|*Description*
{set:cellbgcolor:lightblue}
2+|Archetypes act as the configuration basis for the particular structures of instances defined by the reference model. To enable archetypes to be used to create valid data, key classes in the reference model act as  root  points for archetyping; accordingly, these classes have the archetype_details attribute set.  +
An instance of the class ARCHETYPED contains the relevant archetype identification information, allowing generating archetypes to be matched up with data instances.
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*archetype_id*: `ARCHETYPE_ID`
{set:cellbgcolor!}
|Globally unique archetype identifier. 

|*0..1*
{set:cellbgcolor:lightblue}
|*template_id*: `TEMPLATE_ID`
{set:cellbgcolor!}
|Globally unique template identifier, if a template was active at this point in the structure. Normally, a template would only be used at the top of a top-level structure, but the possibility exists for templates at lower levels. 

|*1..1*
{set:cellbgcolor:lightblue}
|*rm_version*: `String`
{set:cellbgcolor!}
|Version of the openEHR reference model used to create this object. Expressed in terms of the release version string, e.g.  1.0 ,  1.2.4 .

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Rm_version_valid_*: not rm_version.is_empty
{set:cellbgcolor!}
|===
