=== AUDIT_DETAILS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*AUDIT_DETAILS*

h|*Description*
2+a|The set of attributes required to document the committal of an information item to a repository.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*system_id*: `String`
a|Identifier of the logical EHR system where the change was committed. This is almost always owned by the organisation legally responsible for the EHR, and is distinct from any application, or any hosting infrastructure.

h|*1..1*
|*time_committed*: `DV_DATE_TIME`
a|Time of committal of the item.

h|*1..1*
|*change_type*: `DV_CODED_TEXT`
a|Type of change. Coded using the openEHR Terminology  audit change type  group.

h|*0..1*
|*description*: `DV_TEXT`
a|Reason for committal. This may be used to qualify the value in the `_change_type_` field. For example, if the change affects only the EHR directory, this field might be used to indicate 'Folder "episode 2018-02-16" added' or similar.

h|*1..1*
|*committer*: `PARTY_PROXY`
a|Identity and optional reference into identity management service, of user who committed the item.

h|*Invariants*
2+a|*_System_id_valid_*: `not system_id.is_empty`

h|
2+a|*_Change_type_valid_*: `terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_audit_change_type, change_type.defining_code)`
|===
