=== DECISION_GROUP Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DECISION_GROUP*

h|*Description*
2+a|A specialised node that represents a decision point in guideline-based Task Plan definition. The decision is represented by the value_expression, which at runtime is instantiated as an ASSIGNMENT.

Instances of this class also act as a container for the subordinate decision paths which are modelled as TASK_GROUPs with execution_type = decisional, and each having a precondition representing a match expression for the value generated by the value_expression on the parent DECISION_GROUP object.

h|*Inherit*
2+|`PLAN_ITEM`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value_expression*: `DV_PARSABLE`
a|An expression in the form of a variable assignment from an expression or a plain variable reference, if no expression is required. The same variable will appear in the test_expressions of all immediate child paths. Each of these expressions must have mutually exclusive value ranges to be valid.

h|*1..1*
|*paths*: `List<DECISION_PATH_GROUP>`
a|Set of Task Groups that are also decision paths in this Decision Group.
|===
