=== DEFINED_TASK Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DEFINED_TASK*

h|*Description*
2+a|Task sub-type that represents concretely defined work items. The definition of the work of the Task is expressed in terms of archetype of an ENTRY (usually an ACTION) that will be used to record the Task's execution.

The entry_instance attribute can be used to record a forward reference to an ACTION or other ENTRY when it has been recorded.

h|*Inherit*
2+|`TASK`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*prototype*: `List<ENTRY>`
a|Prototype instance of one or more Entries that express the specific work of the Task. Normally one Entry would be used, typically an ACTION, but more than one may sometimes make sense, e.g. an ACTION and an OBSERVATION.

h|*0..1*
|*review_dataset*: `List<DATASET_SPEC>`
a|Optional data-set to review prior to / as part of performing Task. This implies a data retrieval from the EHR or other system, which may be specified using a SYSTEM_REQUEST attached to this Task.

h|*0..1*
|*capture_dataset*: `List<DATASET_SPEC>`
a|Associated data-set template and/or form via which data to be captured during this Task will actually be entered.

h|*0..1*
|*optionality*: `VALIDITY_KIND`
a|Informal indication of whether Task is considered optional or not from the point of view of any guideline. If not set, the Task is treated as mandatory.

TODO: is this useful or meaningful, since it can change
|===
