=== DV_COUNT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_COUNT*

h|*Description*
2+a|Countable quantities. Used for countable types such as pregnancies and steps (taken by a physiotherapy patient), number of cigarettes smoked in a day.

Misuse: Not to be used for amounts of physical entities (which all have units).

h|*Inherit*
2+|`DV_AMOUNT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*magnitude*: `Integer64`
a|

h|*0..1 +
(redefined)*
|*normal_range*: `DV_INTERVAL<DV_COUNT>`
a|Optional normal range.

h|*0..1 +
(redefined)*
|*other_reference_ranges*: `List<REFERENCE_RANGE<DV_COUNT>>`
a|Optional tagged other reference ranges for this value in its particular measurement context.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(redefined)
|*add* _alias_ "+" ( +
other: `DV_COUNT[1]` +
): `DV_COUNT`
a|Sum of this `DV_COUNT` and `_other_`.

h|(redefined)
|*subtract* _alias_ "-" ( +
other: `DV_COUNT[1]` +
): `DV_COUNT`
a|Difference of this `DV_COUNT` and `_other_`.

h|(redefined)
|*multiply* _alias_ "&#42;" ( +
factor: `Real[1]` +
): `DV_COUNT`
a|Product of this `DV_COUNT` and `_factor_`.

h|(effected)
|*less_than* _alias_ "<" ( +
other: `DV_COUNT[1]` +
): `Boolean` +
 +
_Post_result_: `Result = magnitude > other.magnitude`
a|True if `_other_` is less than this Quantified object. Based on comparison of `_magnitude_`.

h|(effected)
|*is_strictly_comparable_to* ( +
other: `DV_ORDERED[1]` +
): `Boolean`
a|Return True.
|===
