=== DV_DURATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_DURATION*

h|*Description*
2+a|Represents a period of time with respect to a notional point in time, which is not specified. A sign may be used to indicate the duration is  backwards  in time rather than forwards.

NOTE: a deviation from ISO8601 is supported, allowing the  W' designator to be mixed with other designators. See primitive types section in the Foundation Types model.

Used for recording the duration of something in the real world, particularly when there is a need a) to represent the duration in customary format, i.e. days, hours, minutes etc, and b) if it will be used in computational operations with date/time quantities, i.e. additions, subtractions etc.

Misuse: Durations cannot be used to represent points in time, or intervals of time.

h|*Inherit*
2+|`DV_AMOUNT`, `Iso8601_duration`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*value*: `String`
a|ISO8601 duration string.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(redefined)
|*add* _alias_ "+" ( +
other: `DV_DURATION[1]` +
): `DV_DURATION`
a|Sum of this Duration and `_other_`.

h|(redefined)
|*subtract* _alias_ "-" ( +
other: `DV_DURATION[1]` +
): `DV_DURATION`
a|Difference of this Duration and `_other_`.

h|(redefined)
|*multiply* _alias_ "&#42;" ( +
factor: `Real[1]` +
): `DV_DURATION`
a|Product of this Duration and `_factor_`.

h|(effected)
|*less_than* _alias_ "<" ( +
other: `DV_DURATION[1]` +
): `Boolean` +
 +
_Post_result_: `Result = magnitude < other.magnitude`
a|True if `_other_` is less than this Quantified object. Based on comparison of `_magnitude_`.

h|(effected)
|*is_strictly_comparable_to* ( +
other: `DV_DURATION[1]` +
): `Boolean`
a|True, for any two Durations.

h|*Invariants*
2+a|_Value_valid_: `valid_iso8601_duration (value)`
|===
