=== DV_DURATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_DURATION*

h|*Description*
2+a|Represents a period of time with respect to a notional point in time, which is not specified. A sign may be used to indicate the duration is  backwards  in time rather than forwards.

NOTE: two deviations from ISO 8601 are supported, the first, to allow a negative sign, and the second allowing the 'W' designator to be mixed with other designators. See time types section in the Foundation Types model.

Used for recording the duration of something in the real world, particularly when there is a need a) to represent the duration in customary format, i.e. days, hours, minutes etc, and b) if it will be used in computational operations with date/time quantities, i.e. additions, subtractions etc.

Misuse: Durations cannot be used to represent points in time, or intervals of time.

h|*Inherit*
2+|`<<_dv_amount_class,DV_AMOUNT>>`, `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*value*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|ISO8601 duration string, including described deviations to support negative values and weeks.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
other: `<<_dv_duration_class,DV_DURATION>>[1]` +
): `<<_dv_duration_class,DV_DURATION>>`
a|Sum of this Duration and `_other_`.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
other: `<<_dv_duration_class,DV_DURATION>>[1]` +
): `<<_dv_duration_class,DV_DURATION>>`
a|Difference of this Duration and `_other_`.

h|*1..1 +
(redefined)*
|*multiply* __alias__ "&#42;" ( +
factor: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^][1]` +
): `<<_dv_duration_class,DV_DURATION>>`
a|Product of this Duration and `_factor_`.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_dv_duration_class,DV_DURATION>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]` +
 +
__Post_result__: `Result = magnitude < other.magnitude`
a|True if `_other_` is less than this Quantified object. Based on comparison of `_magnitude_`.

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `<<_dv_duration_class,DV_DURATION>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True, for any two Durations.

h|*1..1 +
(redefined)*
|*negative* __alias__ "-" (): `<<_dv_duration_class,DV_DURATION>>`
a|Negated version of current duration.

Assuming the current duration is positive, the negated version represents a time prior to some origin point, or a negative age (e.g. so-called 'adjusted age' of premature infant).

h|*1..1 +
(effected)*
|*magnitude* (): `link:/releases/BASE/{base_release}/foundation_types.html#_double_class[Double^]`
a|Numeric value of the duration as a number of seconds. Computed using the method `_to_seconds()_` inherited from `Iso8601_duration`.

h|*Invariants*
2+a|__Value_valid__: `valid_iso8601_duration (value)`
|===
