=== DV_DATE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_DATE*

h|*Description*
2+a|Represents an absolute point in time, as measured on the Gregorian calendar, and specified only to the day. Semantics defined by ISO 8601. Used for recording dates in real world time. The partial form is used for approximate birth dates, dates of death, etc.

h|*Inherit*
2+|`<<_dv_temporal_class,DV_TEMPORAL>>`, `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_class[Iso8601_date^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*value*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|ISO8601 date string.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*magnitude* (): `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Numeric value of the date as days since the calendar origin date `0001-01-01`.

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_dv_quantified_class,DV_QUANTIFIED>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Return True if this `DV_QUANTIFIED` is considered equal to `_other_`.

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
a_diff: `<<_dv_duration_class,DV_DURATION>>[1]` +
): `<<_dv_date_class,DV_DATE>>`
a|Addition of a Duration to this Date.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
a_diff: `<<_dv_duration_class,DV_DURATION>>[1]` +
): `<<_dv_date_class,DV_DATE>>`
a|Subtract a Duration from this Date.

h|*1..1 +
(redefined)*
|*diff* __alias__ "-" ( +
other: `<<_dv_date_class,DV_DATE>>[1]` +
): `<<_dv_duration_class,DV_DURATION>>`
a|Difference between this Date and `_other_`.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_dv_date_class,DV_DATE>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]` +
 +
__Post_result__: `Result = magnitude > other.magnitude`
a|True if `_other_` is less than this Quantified object. Based on comparison of `_magnitude_`.

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `<<_dv_date_class,DV_DATE>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True, for any two Dates.

h|*Invariants*
2+a|__Value_valid__: `valid_iso8601_date(value)`
|===
