=== DV_DATE_TIME Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_DATE_TIME*

h|*Description*
2+a|Represents an absolute point in time, specified to the second. Semantics defined by ISO 8601.

Used for recording a precise point in real world time, and for approximate time stamps, e.g. the origin of a `HISTORY` in an `OBSERVATION` which is only partially known.

h|*Inherit*
2+|`DV_TEMPORAL`, `Iso8601_date_time`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*value*: `String`
a|ISO8601 date/time string.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*magnitude* (): `double`
a|Numeric value of the date/time as seconds since the calendar origin date/time `0001-01-01T00:00:00Z`.

h|(effected)
|*add* ( +
a_diff: `DV_DURATION[1]` +
): `DV_DATE_TIME`
a|Addition of a Duration to this Date/time.

h|(effected)
|*subtract* ( +
a_diff: `DV_DURATION[1]` +
): `DV_DATE_TIME`
a|Subtract a Duration from this Date/time.

h|(effected)
|*diff* ( +
other: `DV_DATE_TIME[1]` +
): `DV_DURATION`
a|Difference between this Date/time and `_other_`.

h|(effected)
|*less_than* ( +
other: `DV_DATE_TIME[1]` +
): `Boolean` +
*_Post_result_*: `Result = magnitude > other.magnitude`
a|True if `_other_` is less than this Quantified object. Based on comparison of `_magnitude_`.

h|(effected)
|*is_strictly_comparable_to* ( +
other: `DV_DATE_TIME[1]` +
): `Boolean`
a|True, for any two Date/times.

h|*Invariants*
2+a|*_Value_valid_*: `valid_iso8601_date_time (value)`
|===
