=== DV_DATE_TIME Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_DATE_TIME*

h|*Description*
2+a|Represents an absolute point in time, specified to the second. Semantics defined by ISO 8601.

Used for recording a precise point in real world time, and for approximate time stamps, e.g. the origin of a HISTORY in an OBSERVATION which is only partially known.

h|*Inherit*
2+|`<<_dv_temporal_class,DV_TEMPORAL>>`, `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*value*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|ISO8601 date/time string.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*magnitude* (): `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^]`
a|Numeric value of the date/time as seconds since the calendar origin point.

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `<<_dv_ordered_class,DV_ORDERED>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Test if two instances are strictly comparable.

h|*1..1 +
(effected)*
|*add* ( +
a_diff: `<<_dv_amount_class,DV_AMOUNT>>[1]` +
): `<<_dv_absolute_quantity_class,DV_ABSOLUTE_QUANTITY>>`
a|Add a time period to this date_time.

h|*1..1 +
(effected)*
|*subtract* ( +
a_diif: `<<_dv_amount_class,DV_AMOUNT>>[1]` +
): `<<_dv_absolute_quantity_class,DV_ABSOLUTE_QUANTITY>>`
a|Subtract a time period from this date_time.

h|*1..1 +
(effected)*
|*diff* ( +
other: `<<_dv_absolute_quantity_class,DV_ABSOLUTE_QUANTITY>>[1]` +
): `<<_dv_amount_class,DV_AMOUNT>>`
a|Difference of two quantities.

h|*1..1*
|*operator=* ( +
source: `<<_dv_date_time_class,DV_DATE_TIME>>[1]` +
): `<<_dv_date_time_class,DV_DATE_TIME>>`
a|

h|*1..1 +
(redefined)*
|*as_string* (): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|

h|*Invariants*
2+a|__Value_valid__: `valid_iso8601_date_time (value)`
|===
