=== DV_DURATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_DURATION*

h|*Description*
2+a|Represents a period of time with respect to a notional point in time, which is not specified. A sign may be used to indicate the duration is  backwards  in time rather than forwards.

NOTE: a deviation from ISO8601 is supported, allowing the  W' designator to be mixed with other designators. See assumed types section in the Support IM.

Used for recording the duration of something in the real world, particularly when there is a need a) to represent the duration in customary format, i.e. days, hours, minutes etc, and b) if it will be used in computational operations with date/time quantities, i.e. additions, subtractions etc.

Misuse: Durations cannot be used to represent points in time, or intervals of time.

h|*Inherit*
2+|`<<_dv_amount_class,DV_AMOUNT>>`, `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*value*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|ISO8601 duration string
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `<<_dv_ordered_class,DV_ORDERED>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|

h|*Invariants*
2+a|__Value_valid__: `valid_iso8601_duration (value)`
|===
