=== DV_ENCAPSULATED Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*_DV_ENCAPSULATED (abstract)_*

h|*Description*
2+a|Abstract class defining the common meta-data of all types of encapsulated data.

h|*Inherit*
2+|DATA_VALUE

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*charset*: `CODE_PHRASE`
a|Name of character encoding scheme in which this value is encoded. Coded from openEHR Code Set  character sets . Unicode is the default assumption in openEHR, with UTF-8 being the assumed encoding. This attribute allows for variations from these assumptions. 

h|*0..1*
|*language*: `CODE_PHRASE`
a|Optional indicator of the localised language in which the data is written, if relevant. Coded from openEHR Code Set  languages.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*size*: `Integer`
a|Original size in bytes of unencoded encapsulated data. I.e. encodings such as base64, hexadecimal etc. do not change the value of this attribute. 

h|*Invariant*
2+a|*_Size_valid_*: size >= 0

h|
2+a|*_Language_valid_*: language /= Void implies code_set (Code_set_id_languages).has_code (language)

h|
2+a|*_Charset_valid_*: charset /= Void implies code_set (Code_set_id_character_sets).has_code (charset)
|===
