=== DV_IDENTIFIER Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*DV_IDENTIFIER*

|*Description*
{set:cellbgcolor:lightblue}
2+|Type for representing identifiers of real-world entities. Typical identifiers include drivers licence number, social security number, veterans affairs number, prescription id, order id, and so on. +
DV_IDENTIFIER is used to represent any identifier of a real thing, issued by some authority or agency.  +
DV_IDENTIFIER is not used to express identifiers generated by the infrastructure to refer to information items; the types OBJECT_ID and OBJECT_REF and subtypes are defined for this purpose.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|DATA_VALUE
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*issuer*: `String`
{set:cellbgcolor!}
|Authority which issues the kind of id used in the id field of this object. 

|*1..1*
{set:cellbgcolor:lightblue}
|*assigner*: `String`
{set:cellbgcolor!}
|Organisation that assigned the id to the item being identified.

|*1..1*
{set:cellbgcolor:lightblue}
|*id*: `String`
{set:cellbgcolor!}
|The identifier value. Often structured, according to the definition of the issuing authority's rules. 

|*1..1*
{set:cellbgcolor:lightblue}
|*type*: `String`
{set:cellbgcolor!}
|The identifier type, such as  prescription , or  Social Security Number . One day a controlled vocabulary might be possible for this.
|===
