=== DV_ORDINAL Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_ORDINAL*

h|*Description*
2+a|A data type that represents integral score values, e.g. pain, Apgar values, etc, where there is:

a) implied ordering,
b) no implication that the distance between each value is constant, and
c) the total number of values is finite;
d) integer values only.

Note that although the term 'ordinal' in mathematics means natural numbers only, here any integer is allowed, since negative and zero values are often used by medical professionals for values around a neutral point. Examples of sets of ordinal values:

*   -3, -2, -1, 0, 1, 2, 3  -- reflex response values
*    0, 1, 2                  -- Apgar values

This class is used for recording any clinical datum which is customarily recorded using symbolic values. Example: the results on a urinalysis strip, e.g. `{neg, trace, +, ++, +++}` are used for leucocytes, protein, nitrites etc; for non-haemolysed blood `{neg, trace, moderate}`; for haemolysed blood `{small, moderate, large}`.

For scores or scales that include Real numbers (or might in the future, i.e. not fixed for all time, such as Apgar), use `DV_SCALE`. `DV_SCALE` may also be used in future for representing purely Integer-based scales, however, the `DV_ORDINAL` type should continue to be supported in software implementations in order to accommodate existing data that are instances of this type.

h|*Inherit*
2+|`<<_dv_ordered_class,DV_ORDERED>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*symbol*: `<<_dv_coded_text_class,DV_CODED_TEXT>>`
a|Coded textual representation of this value in the enumeration, which may be strings made from  +  symbols, or other enumerations of terms such as  `mild`, `moderate`, `severe`, or even the same number series as the values, e.g. 1, 2, 3.

h|*1..1*
|*value*: `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Value in ordered enumeration of values. Any integer value can be used.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_dv_ordinal_class,DV_ORDINAL>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]` +
 +
__Pre_comparable__: `is_strictly_comparable_to (other)`
a|True if this Ordinal value is less than `_other_`.

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `<<_dv_ordinal_class,DV_ORDINAL>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Test if this Ordinal is strictly comparable to `_other_`.
|===
