=== DV_ORDINAL Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*DV_ORDINAL*

|*Description*
{set:cellbgcolor:lightblue}
2+|Models rankings and scores, e.g. pain, Apgar values, etc, where there is a) implied ordering, b) no implication that the distance between each value is constant, and c) the total number of values is finite. Note that although the term  ordinal' in mathematics means natural numbers only, here any integer is allowed, since negative and zero values are often used by medical professionals for values around a neutral point. Examples of sets of ordinal values:  +
*   -3, -2, -1, 0, 1, 2, 3  -- reflex response values  +
*    0, 1, 2                  -- Apgar values  +
This class is used for recording any clinical datum which is customarily recorded using symbolic values. Example: the results on a urinalysis strip, e.g. {neg, trace, +, ++, +++} are used for leucocytes, protein, nitrites etc; for non-haemolysed blood {neg, trace, moderate}; for haemolysed blood small, moderate, large}. 
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|DV_ORDERED
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*symbol*: `DV_CODED_TEXT`
{set:cellbgcolor!}
|Coded textual representation of this value in the enumeration, which may be strings made from  +  symbols, or other enumerations of terms such as  mild ,  moderate ,  severe , or even the same number series as the values, e.g.  1 ,  2 ,  3 . Codes come from archetype. 

|*1..1*
{set:cellbgcolor:lightblue}
|*value*: `Integer`
{set:cellbgcolor!}
|Value in ordered enumeration of values. Any integer value can be used. 
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*limits*: `DV_ORDINAL`
{set:cellbgcolor!}
|Limits of the ordinal enumeration, to allow comparison of an ordinal  +
value to its limits. 

|
{set:cellbgcolor:lightblue}
|*<* (other: `Ordered`): `Boolean` +
*_Post_*: Result = value < other.value
{set:cellbgcolor!}
|

|(effected)
{set:cellbgcolor:lightblue}
|*is_strictly_comparable_to* (other: `DV_ORDERED`): `Boolean` +
*_Post_*: symbol.is_comparable (other.symbol) implies Result
{set:cellbgcolor!}
|

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Limits_valid_*: limits.meaning.is_equal (“limits”)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Reference_range_valid_*: other_reference_ranges.has (limits)
{set:cellbgcolor!}
|===
