=== DV_PROPORTION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_PROPORTION*

h|*Description*
2+a|Models a ratio of values, i.e. where the numerator and denominator are both pure numbers. The valid_proportion_kind property of the PROPORTION_KIND class is
used to control the type attribute to be one of a defined set.

Used for recording titers (e.g. 1:128), concentration ratios, e.g. Na:K (unitary denominator), albumin:creatinine ratio, and percentages, e.g. red cell distirbution width (RDW).

Misuse: Should not be used to represent things like blood pressure which are often written using a  '/' character, giving the misleading impression that the item is a ratio, when in fact it is a structured value. Similarly, visual acuity, often written as (e.g.) “6/24” in clinical notes is not a ratio but an ordinal (which includes non-numeric symbols like CF = count fingers etc). Should not be used for formulations.

h|*Inherit*
2+|`<<_proportion_kind_class,PROPORTION_KIND>>`, `<<_dv_amount_class,DV_AMOUNT>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*numerator*: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^]`
a|Numerator of ratio

h|*1..1*
|*denominator*: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^]`
a|Denominator of ratio.

h|*1..1*
|*type*: `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Indicates semantic type of proportion, including percent, unitary etc.

h|*0..1*
|*precision*: `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Precision  to  which  the  numerator and denominator values of  the  proportion are expressed, in terms of number  of  decimal places. The value 0 implies an integral quantity. The value -1 implies no limit, i.e. any number of decimal places.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*magnitude* (): `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^]`
a|Effective magnitude represented by ratio.

h|*1..1*
|*is_integral* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if the numerator and denominator values are integers, i.e. if the precision is 0.

h|*1..1*
|*operator=* ( +
source: `<<_dv_proportion_class,DV_PROPORTION>>[1]` +
): `<<_dv_proportion_class,DV_PROPORTION>>`
a|Assignment operator

h|*Invariants*
2+a|__Type_validity__: `valid_proportion_kind (type)`

h|
2+a|__Precision_validity__: `precision = 0 implies is_integral`

h|
2+a|__Is_integral_validity__: `is_integral implies (numerator.floor = numerator and denominator.floor = denominator)`

h|
2+a|__Fraction_validity__: `(type = pk_fraction or type = pk_integer_fraction) implies is_integral`

h|
2+a|__Unitary_validity__: `type = pk_unitary implies denominator = 1`

h|
2+a|__Percent_validity__: `type = pk_percent implies denominator = 100`
|===
