=== DV_QUANTIFIED Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__DV_QUANTIFIED (abstract)__*

h|*Description*
2+a|Abstract class defining the concept of true quantified values, i.e. values which are not only ordered, but which have a precise magnitude.

h|*Inherit*
2+|`<<_dv_ordered_class,DV_ORDERED>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*magnitude_status*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Optional status of magnitude with values:

* =   :   magnitude is a point value
* <   :   value is < magnitude
* >   :   value is > magnitude
* \\<= : value is \<= magnitude
* >= : value is >= magnitude
* ~   :   value is approximately magnitude

If not present, meaning is  = .

h|*0..1*
|*accuracy*: `link:/releases/BASE/{base_release}/foundation_types.html#_any_class[Any^]`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*valid_magnitude_status* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]` +
 +
__Post__: `Result = s.is_equal (“=”) or s.is_equal (“<”) or s.is_equal (“>”) or s.is_equal (“\<=”) or s.is_equal (“>=”) or s.is_equal (“~”)`
a|Test whether a string value is one of the valid values for the magnitude_status attribute.

h|*1..1 +
(abstract)*
|*magnitude* (): `link:/releases/BASE/{base_release}/foundation_types.html#_ordered_numeric_class[Ordered_Numeric^]`
a|

h|*1..1*
|*accuracy_unknown* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if accuracy is not known, e.g. due to not being recorded or discernable.

h|*Invariants*
2+a|__Magnitude_status_valid__: `magnitude_status /= Void implies valid_magnitude_status (magnitude_status)`
|===
