=== DV_QUANTITY Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*DV_QUANTITY*

|*Description*
{set:cellbgcolor:lightblue}
2+|Quantitified type representing  scientific  quantities, i.e. quantities expressed as a magnitude and units.  Units were inspired by the Unified Code for Units of Measure (UCUM), developed by Gunther Schadow and Clement J. McDonald of The Regenstrief Institute.  +
Can also be used for time durations, where it is more convenient to treat these as simply a number of seconds rather than days, months, years. 
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|DV_AMOUNT
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*magnitude*: `Real`
{set:cellbgcolor!}
|Numeric magnitude of the quantity.

|*0..1*
{set:cellbgcolor:lightblue}
|*precision*: `Integer`
{set:cellbgcolor!}
|Precision to which the value of the quantity is expressed, in terms of number of decimal places. The value 0 implies an integral quantity. +
The value -1 implies no limit, i.e. any number of decimal places.

|*1..1*
{set:cellbgcolor:lightblue}
|*units*: `String`
{set:cellbgcolor!}
|Stringified units, expressed in UCUM unit syntax, e.g. "kg/m2", “mm[Hg]", "ms-1", "km/h". Implemented accordingly in subtypes.
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*is_integral*: `Boolean`
{set:cellbgcolor!}
|
|===
