=== DV_QUANTIFIED Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*_DV_QUANTIFIED (abstract)_*

|*Description*
{set:cellbgcolor:lightblue}
2+|Abstract class defining the concept of true quantified values, i.e. values which are not only ordered, but which have a precise magnitude.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|DV_ORDERED
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*0..1*
{set:cellbgcolor:lightblue}
|*magnitude_status*: `String`
{set:cellbgcolor!}
|Optional status of magnitude with values:  +
     =  :   magnitude is a point value  +
     <  :   value is < magnitude  +
     >  :   value is > magnitude  +
     <=  : value is <= magnitude  +
     >=  : value is >= magnitude  +
     ~  :   value is approximately magnitude  +
If not present, meaning is  = . 
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*valid_magnitude_status*: `Boolean`
{set:cellbgcolor!}
|Test whether a string value is one of the valid values for the magnitude_status attribute. 

|
{set:cellbgcolor:lightblue}
|*magnitude*: `Ordered_Numeric`
{set:cellbgcolor!}
|
|===
