=== DV_SCALE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_SCALE*

h|*Description*
2+a|A data type that represents scale values, where there is:

a) implied ordering,
b) no implication that the distance between each value is constant, and
c) the total number of values is finite;
d) non-integer values are allowed.

Example:

----
Borg CR 10 Scale

0    No Breathlessness at all
0.5  Very Very Slight (Just Noticeable)
1    Very Slight
2    Slight Breathlessness
3    Moderate
... etc
----

For scores that include only Integers, `DV_SCALE` may also be used, but `DV_ORDINAL` should be supported to accommodate existing data instances of that type.

h|*Inherit*
2+|`DV_ORDERED`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*symbol*: `DV_CODED_TEXT`
a|Coded textual representation of this value in the scale range, which may be strings made from symbols or other enumerations of terms such as  `no breathlessness`, `very very slight`, `slight breathlessness`. Codes come from archetypes.

In some cases, a scale may include values that have no code/symbol. In this case, the symbol will be a `DV-CODED_TEXT` including the `_terminology_id_` and a blank String value for `_code_string_`.

h|*1..1*
|*value*: `Real`
a|Real number value of Scale item.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*is_strictly_comparable_to* ( +
other: `DV_SCALE[1]` +
): `Boolean`
a|Test if this Scale value is strictly comparable to `_other_`.

h|(effected)
|*less_than* _alias_ "<" ( +
other: `DV_SCALE[1]` +
): `Boolean` +
 +
_Pre_comparable_: `is_strictly_comparable (other)`
a|True if this Scale value is less than `_other_`.
|===
