=== DV_TIME Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_TIME*

h|*Description*
2+a|Represents an absolute point in time from an origin usually interpreted as meaning the start of the current day, specified to a fraction of a second. Semantics defined by ISO 8601.

Used for recording real world times, rather than scientifically measured fine amounts of time. The partial form is used for approximate times of events and substance administrations.

h|*Inherit*
2+|`DV_TEMPORAL`, `Iso8601_time`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*value*: `String`
a|ISO8601 time string
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*magnitude* (): `Real`
a|Numeric value of the time as seconds since the start of day, i.e. `00:00:00`.

h|*1..1 +
(redefined)*
|*add* _alias_ "+" ( +
a_diff: `DV_DURATION[1]` +
): `DV_TIME`
a|Addition of a Duration to this Time.

h|*1..1 +
(redefined)*
|*subtract* _alias_ "-" ( +
a_diff: `DV_DURATION[1]` +
): `DV_TIME`
a|Subtract a Duration from this Time.

h|*1..1 +
(redefined)*
|*diff* _alias_ "-" ( +
other: `DV_TIME[1]` +
): `DV_DURATION`
a|Difference between this Time and `_other_`.

h|*1..1 +
(effected)*
|*less_than* _alias_ "<" ( +
other: `DV_TIME[1]` +
): `Boolean` +
 +
_Post_result_: `Result = magnitude > other.magnitude`
a|True if `_other_` is less than this Quantified object. Based on comparison of `_magnitude_`.

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `DV_TIME[1]` +
): `Boolean`
a|True, for any two Times.

h|*Invariants*
2+a|_Value_valid_: `valid_iso8601_time (value)`
|===
