=== EHR Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*EHR*

h|*Description*
2+a|The EHR object is the root object and access point of an EHR for a subject of care.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*system_id*: `link:/releases/RM/{rm_release}/support.html#_hier_object_id_class[HIER_OBJECT_ID^]`
a|The id of the EHR system on which this EHR was created.

h|*1..1*
|*ehr_id*: `link:/releases/RM/{rm_release}/support.html#_hier_object_id_class[HIER_OBJECT_ID^]`
a|The id of this EHR.

h|*0..1*
|*contributions*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/RM/{rm_release}/support.html#_object_ref_class[OBJECT_REF^]>`
a|List of contributions causing changes to this EHR. Each contribution contains a list of versions, which may include references to any number of VERSION instances, i.e. items of type VERSIONED_COMPOSITION and VERSIONED_FOLDER.

h|*1..1*
|*ehr_status*: `link:/releases/RM/{rm_release}/support.html#_object_ref_class[OBJECT_REF^]`
a|Reference to EHR_STATUS object for this EHR.

h|*1..1*
|*ehr_access*: `link:/releases/RM/{rm_release}/support.html#_object_ref_class[OBJECT_REF^]`
a|Reference to EHR_ACCESS object for this EHR.

h|*0..1*
|*compositions*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/RM/{rm_release}/support.html#_object_ref_class[OBJECT_REF^]>`
a|Master list of all Versioned Composition references in this EHR.

h|*0..1*
|*directory*: `link:/releases/RM/{rm_release}/support.html#_object_ref_class[OBJECT_REF^]`
a|Optional directory structure for this EHR.

h|*1..1*
|*time_created*: `link:/releases/RM/{rm_release}/data_types.html#_dv_date_time_class[DV_DATE_TIME^]`
a|Time of creation of the EHR.

h|*Invariants*
2+a|__Contributions_valid__: `contributions.for_all (c &#124; c.type.is_equal(“CONTRIBUTION”))`

h|
2+a|__Ehr_access_valid__: `ehr_access.type.is_equal (“VERSIONED_EHR_ACCESS”)`

h|
2+a|__Ehr_status_valid__: `ehr_status.type.is_equal(“VERSIONED_EHR_STATUS”)`

h|
2+a|__Compositions_valid__: `compositions.for_all (c &#124; c.type.is_equal (“VERSIONED_COMPOSITION”))`

h|
2+a|__Directory_valid__: `directory /= Void implies directory.type.is_equal (“VERSIONED_FOLDER”)`
|===
