=== ELEMENT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*ELEMENT*

h|*Description*
2+a|The leaf variant of `ITEM`, to which a `DATA_VALUE` instance is attached.

h|*Inherit*
2+|`ITEM`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*null_flavour*: `DV_CODED_TEXT`
a|Flavour of null value, e.g. `253&#124;unknown&#124;`, `271&#124;no information&#124;`, `272&#124;masked&#124;`, and `273&#124;not applicable&#124;`.

h|*0..1*
|*value*: `DATA_VALUE`
a|Property representing leaf value object of `ELEMENT`. In real data, any concrete subtype of `DATA_VALUE` can be used.

h|*0..1*
|*null_reason*: `DV_TEXT`
a|Optional specific reason for null value; if set, `_null_flavour_` must be set. Null reason may apply only to a minority of clinical data, commonly needed in reporting contexts.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_null* (): `Boolean`
a|True if value logically not known, e.g. if indeterminate, not asked etc.

h|*Invariants*
2+a|_Inv_is_null_valid_: `is_null() = (value = Void)`

h|
2+a|_Inv_null_flavour_indicated_: `is_null() xor null_flavour = Void`

h|
2+a|_Inv_null_flavour_valid_: `is_null implies terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_null_flavour, null_flavour.defining_code)`

h|
2+a|_Inv_null_reason_valid_: `null_reason /= Void implies is_null()`
|===
