=== ELEMENT Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*ELEMENT*

|*Description*
{set:cellbgcolor:lightblue}
2+|The leaf variant of ITEM, to which a DATA_VALUE instance is attached. 
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|ITEM
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*0..1*
{set:cellbgcolor:lightblue}
|*null_flavor*: `DV_CODED_TEXT`
{set:cellbgcolor!}
|Flavour of null value, e.g. indeterminate, not asked etc.

|*0..1*
{set:cellbgcolor:lightblue}
|*value*: `DATA_VALUE`
{set:cellbgcolor!}
|Data value of this leaf.
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*is_null*: `Boolean`
{set:cellbgcolor!}
|True if value logically not known, e.g. if indeterminate, not asked etc. 

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Is_null_valid_*: is_null = (value = Void)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Null_flavour_indicated_*: is_null xor null_flavour = Void
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Null_flavour_valid_*: is_null implies terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_null_flavour, null_flavour.defining_code)
{set:cellbgcolor!}
|===
