=== ENTRY Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*_ENTRY (abstract)_*

|*Description*
{set:cellbgcolor:lightblue}
2+|The abstract parent of all ENTRY subtypes. An ENTRY is the root of a logical item of  hard  clinical information created in the  clinical statement  context, within a clinical session. There can be numerous such contexts in a clinical session. Observations and other Entry types only ever document information captured/created in the event documented by the enclosing Composition. +
An ENTRY is also the minimal unit of information any query should return, since a whole ENTRY (including subparts) records spatial structure, timing information, and contextual information, as well as the subject and generator of the information. 
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|CONTENT_ITEM
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*language*: `CODE_PHRASE`
{set:cellbgcolor!}
|Mandatory indicator of the localised language in which this Entry is written. Coded from openEHR Code Set  languages . 

|*1..1*
{set:cellbgcolor:lightblue}
|*encoding*: `CODE_PHRASE`
{set:cellbgcolor!}
|Name of character set in which text values in this Entry are encoded. Coded from openEHR Code Set  character sets.

|*0..1*
{set:cellbgcolor:lightblue}
|*other_participations*: `List<PARTICIPATION>`
{set:cellbgcolor!}
|Other participations at ENTRY level. 

|*0..1*
{set:cellbgcolor:lightblue}
|*workflow_id*: `OBJECT_REF`
{set:cellbgcolor!}
|Identifier of externally held workflow engine data for this workflow execution, for this subject of care.

|*1..1*
{set:cellbgcolor:lightblue}
|*subject*: `PARTY_PROXY`
{set:cellbgcolor!}
|Id of human subject of this ENTRY, e.g.:  +
* organ donor  +
* foetus  +
* a family member  +
* another clinically relevant person.

|*0..1*
{set:cellbgcolor:lightblue}
|*provider*: `PARTY_PROXY`
{set:cellbgcolor!}
|Optional identification of provider of the information in this ENTRY, which might be:  +
  * the patient  +
  * a patient agent, e.g. parent, guardian  +
  * the clinician  +
  * a device or software  +
Generally only used when the recorder needs to make it explicit. Otherwise, Composition composer and other participants are assumed. 
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*subject_is_self*: `Boolean` +
*_Post_condition_*: Result implies subject.generating_type = “PARTY_SELF”
{set:cellbgcolor!}
|Returns True if this Entry is about the subject of the EHR, in which case the subject attribute is of type PARTY_SELF.

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Language_valid_*: code_set (Code_set_id_languages).has_code (language)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Encoding_valid_*: code_set (Code_set_id_character_sets).has_code (encoding)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Subject_validity_*: subject_is_self implies subject.generating_type = “PARTY_SELF”
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Other_participations_valid_*: other_participations /= Void implies not other_participations.is_empty
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Is_archetype_root_*: is_archetype_root
{set:cellbgcolor!}
|===
