=== EXTRACT_UPDATE_SPEC Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*EXTRACT_UPDATE_SPEC*

|*Description*
{set:cellbgcolor:lightblue}
2+|Specification of the how the request should be processed by server. The request can be persisted in the server, meaning that a) it can be re-activated by the requesting system simply by indicating Request id, and b) that a changes-only pattern of Extract updates can be set up. To achieve this, the server has to remember what was send in the previous reponse. +
The update mode may be event-driven and periodic update or a mixture of both. The candidate items to be sent each time are the result of re-evaluating the content and versioning parts of the specification; what is actually sent is determined by the send_changes_only flag.
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*persist_in_server*: `Boolean`
{set:cellbgcolor!}
|If True, this Request is persisted in the server until further notice.

|*0..1*
{set:cellbgcolor:lightblue}
|*repeat_period*: `DV_DURATION`
{set:cellbgcolor!}
|Period for resending update Extracts in response to original Request.

|*0..1*
{set:cellbgcolor:lightblue}
|*trigger_events*: `List<DV_CODED_TEXT>`
{set:cellbgcolor!}
|Set of Event names that will cause sending of update Extracts. Event types include:   
  \|any_change\| - any change in content items matched by content specification, e.g. new versions of persistent compositions. If the content list allows matching of any, or a wide range of archetypes, this event type will match any additions to the record. +
  \|correction\| - match error corrections only, including deletions. +
  \|update\| - match updates (i.e. new versions) of included content items.

|*1..1*
{set:cellbgcolor:lightblue}
|*update_method*: `CODE_PHRASE`
{set:cellbgcolor!}
|Indicate mode of update. Can be: send only items that are changed (including logical deletions) or new since last send. For persist_in_server Requests only.

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Overall_validity_*: repeat_period /= Void or trigger_events /= Void
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Trigger_events_validity_*: trigger_events /= Void implies not trigger_events.is_empty
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Send_changes_only_validity_*: send_changes_only implies persist_in_server
{set:cellbgcolor!}
|===
