=== EXTRACT_ENTITY_MANIFEST Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*EXTRACT_ENTITY_MANIFEST*

h|*Description*
2+a|The manifest for one entity, identifying the entity and optionally specifying toplevel items to be included in the Extract. The list actually included may be modified by the version_spec part of the specification, and also by the link_depth attribute. In repeat (standing order) requests, the final inclusion may be modified by the send_changes_only flag of the update_spec.

Various identifiers may be provided for the entity; these are to be used by the receiver system to locate the entity. The extract_id_key attribute is used to record the identifier that will be used throughout the Extract for this entity, including in instances of EXTRACT_ENTITY_IDENTIFIER.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*extract_id_key*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Identifier by which this entity is known in the Extract. May be one of the other identifiers, e.g. ehr_id or subject_id, or it may be something else, including a simple integer.

h|*0..1*
|*ehr_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|EHR / EMR identifier for the entity at the target system.

h|*0..1*
|*subject_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Subject (i.e. patient or similar) identifier for the entity at the target system.

h|*0..1*
|*other_ids*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]>`
a|Other identifiers that may be used to find the entity at the target system, keyed by type. May include medicare numbers, drivers license number, tax number etc.

h|*0..1*
|*item_list*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/RM/{rm_release}/support.html#_object_ref_class[OBJECT_REF^]>`
a|List of uids of items included in the Extract; for openEHR data, these are uids identifying the version containers.
|===
