=== INSTRUCTION_DETAILS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*INSTRUCTION_DETAILS*

h|*Description*
2+a|Used to record details of the Instruction causing an Action.

h|*Inherit*
2+|`link:/releases/RM/{rm_release}/common.html#_pathable_class[PATHABLE^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*instruction_id*: `link:/releases/BASE/{base_release}/base_types.html#_locatable_ref_class[LOCATABLE_REF^]`
a|Reference to causing Instruction.

h|*1..1*
|*activity_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Identifier of Activity within Instruction, in the form of its archetype path.

h|*0..1*
|*wf_details*: `link:/releases/RM/{rm_release}/data_structures.html#_item_structure_class[ITEM_STRUCTURE^]`
a|Various workflow engine state details, potentially including such things as:

* condition that fired to cause this Action to be done (with actual variables substituted);
* list of notifications which actually occurred (with all variables substituted);
* other workflow engine state.

This specification does not currently define the actual structure or semantics of this field.

h|*Invariants*
2+a|__Activity_path_valid__: `not activity_id.is_empty`
|===
