=== ITEM_TABLE Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*ITEM_TABLE*

|*Description*
{set:cellbgcolor:lightblue}
2+|Logical relational database style table data structure, in which columns are named and ordered with respect to each other. Implemented using Cluster-per-row encoding. Each row Cluster must have an identical number of Elements, each of which in turn must have identical names and value types in the corresponding positions in each row.  +
Some columns may be designated  key' columns, containing key data for each row, in the manner of relational tables. This allows row-naming, where each row represents a body site, a blood antigen etc. All values in a column have the same data type.  +
Used for representing any data which is logically a table of values, such as blood pressure, most protocols, many blood tests etc.  +
Not to be used for time-based data, which should be represented with the temporal class HISTORY.. The table may be empty. 
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|ITEM_STRUCTURE
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*0..1*
{set:cellbgcolor:lightblue}
|*rows*: `CLUSTER`
{set:cellbgcolor!}
|Physical representation of the table as a list of CLUSTERs, each containing the data of one row of the table. 
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|(effected)
{set:cellbgcolor:lightblue}
|*as_hierarchy*: `CLUSTER`
{set:cellbgcolor!}
|Generate a CEN EN13606-compatible hierarchy consisting of a single CLUSTER containing the CLUSTERs representing the columns of this table. 
|===
