=== SYNC_EXTRACT_SPEC Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*SYNC_EXTRACT_SPEC*

h|*Description*
2+a|Details of specification of Extract, used in a request to specify an Extract, or in a response, to describe what is actually in the Extract.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*includes_versions*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if the Versions from the Contribution are included; False if just the Contribution and its Audit are included.

h|*0..1*
|*contribution_list*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/base_types.html#_hier_object_id_class[HIER_OBJECT_ID^]>`
a|List of Contributions to include / that are included in the Extract.

h|*0..1*
|*contributions_since*: `link:/releases/RM/{rm_release}/data_types.html#_dv_date_time_class[DV_DATE_TIME^]`
a|Specify Contributions included in Extract by threshold date.

h|*0..1*
|*all_contributions*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if all Contributions in the record are included.
|===
