=== ARTEFACT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*ARTEFACT*

h|*Description*
2+a|An artificial (i.e. manufactured) object with a designed function. Encompasses re-usable / long-term use devices (e.g. heart-rate monitor; ultrasound machine, heart pacemaker) and consumable items designed to be consumed in use, bandage, catheter, drug, food.

A device is considered to be usable until it is determined to be 'worn out' or otherwise not fit for service. This distinguishes it from a consumable, which is considered to be 'used' after one or a small number of uses (the latter situation should be understood as 'one use').

Some consumable items e.g. nasal drip tubes can be physically 'used' more than once with the same patient for a short period of time, but are replaced for different patients and also over longer periods; typically considered consumable.

h|*Inherit*
2+|`<<_independent_object_class,INDEPENDENT_OBJECT>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*function*: `@@`
a|Purpose of the artefact.
|===
