=== ENTITY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__ENTITY (abstract)__*

h|*Description*
2+a|Continuant Entity whose identity is stable over its period of existence. Includes physical entities as well as other kinds of entities from the social, legal and business worlds, including intentional agents.

h|*Inherit*
2+|`link:/releases/RM/{rm_release}/common.html#_locatable_class[LOCATABLE^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*description*: `link:/releases/RM/{rm_release}/data_structures.html#_cluster_class[CLUSTER^]`
a|All other details for this Party.

h|*0..1*
|*type_uri*: `link:/releases/BASE/{base_release}/foundation_types.html#_uri_class[Uri^]`
a|

h|*0..1*
|*relationships*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_relationship_group_class,RELATIONSHIP_GROUP>>>`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*type* (): `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_term_class[Terminology_term^]`
a|Concrete type of entity, such as  `PERSON`,  `ORGANISATION`, etc. Role name, e.g.  general practitioner ,  nurse ,  private citizen . Taken from inherited `_name_` attribute.
|===
