=== PARTY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__PARTY (abstract)__*

h|*Description*
2+a|An independent entity in the social world, often known as a 'party'. Includes all business, civil, military and legal entities.

A Social entity is either an Agent or a 'Persona' (of an Agent). An intentional  agent can participate in an activity, task, process etc, and make decisions.

Theoretically equivalent to `BFO:Realizable` entity, i.e. an s-dependent continuant whose bearer is some physical entity - e.g. a material person, or an aggregate of persons making up a 'company'.

However, we tend to treat social entities in business and civic life, and hence administratively and legally, as being independent entities that stand for their bearers. Concretely, we don't usually represent the related material entity at all.

h|*Inherit*
2+|`<<_social_entity_class,SOCIAL_ENTITY>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*identities*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_party_identity_class,PARTY_IDENTITY>>>`
a|Identities used by the Party to identify itself. Most commonly, Agents will have identity/ies (at least legal name), but occasionally, a Persona will have identities as well, e.g. stage names, aliases, nicknames.

h|*0..1*
|*contacts*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_contact_class,CONTACT>>>`
a|Contacts for this party.

h|*1..1*
|*legal_status*: `@@`
a|Legal status of this entity, potentially supported by documentation (references).

TODO: detail

h|*0..1*
|*capabilities*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_capability_class,CAPABILITY>>>`
a|Capabilities of this Party.

h|*0..1*
|*accountabilities*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_accountability_class,ACCOUNTABILITY>>>`
a|Set of accountabilities defined by this Party. For an Organisation, may be understood as organisational posts, i.e. available jobs.

h|*Invariants*
2+a|__Type_valid__: `type = name`

h|
2+a|__Contacts_valid__: `contacts /= Void implies not contacts.is_empty`

h|
2+a|__Relationships_validity__: `relationships /= Void implies (not relationships.is_empty and then relationships.for_all (r &#124; r.source = self)`

h|
2+a|__Reverse_relationships_validity__: `reverse_relationships /= Void implies (not reverse_relationships.empty and then reverse_relationships.for_all (item &#124; repository ("demographics").all_party_relationships.has_object (item) and then repository("demographics").all_party_relationships.object (item).target = self))`

h|
2+a|__Is_archetype_root__: `is_archetype_root`

h|
2+a|__Uid_mandatory__: `uid /= Void`
|===
