=== AGENT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__AGENT (abstract)__*

h|*Description*
2+a|An intentional agent, equivalent to a mind, either individual or aggregate. An Agent may have one or more Personae, each of which is characterised by one or more Capabilities.

h|*Inherit*
2+|`<<_party_class,PARTY>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*languages*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_terminology_term_class[Terminology_term^]>`
a|Languages which can be used to communicate with this actor, in preferred order of use (if known, else order irrelevant).

h|*0..1*
|*capabilities*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_capability_class,CAPABILITY>>>`
a|Capacities of this Actor.

h|*0..1*
|*accountabilities*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_accountability_class,ACCOUNTABILITY>>>`
a|Set of accountabilities defined by this Actor. For an Organisation, may be understood as organisational posts, i.e. available jobs.

h|*0..1*
|*personae*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_persona_class,PERSONA>>>`
a|Personae of an Agent based on Capabilities. A Persona corresponds to the potential to act in a specific capability-based way, i.e. to have a competency or ability.

For example, the Person Margaret Smith may have a Persona based on her GP (medical) credentials, and another based on her amateur opera singing Capability. She could therefore work as a GP in a health practice and also as a singer in a drama society.
|===
