=== EVENT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__EVENT<T> (abstract)__*

h|*Description*
2+a|Defines the abstract notion of a single event in a series. This class is generic, allowing types to be generated which are locked to particular spatial types, such as `EVENT<ITEM_LIST>`. Subtypes express point or intveral data.

h|*Inherit*
2+|`link:/releases/RM/{rm_release}/common.html#_locatable_class[LOCATABLE^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*time*: `link:/releases/RM/{rm_release}/data_types.html#_dv_date_time_class[DV_DATE_TIME^]`
a|Time of this event. If the width is non-zero, it is the time point of the trailing edge of the event.

h|*0..1*
|*state*: `<<_item_structure_class,ITEM_STRUCTURE>>`
a|Optional state data for this event.

h|*1..1*
|*data*: `T`
a|The data of this event.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*offset* (): `link:/releases/RM/{rm_release}/data_types.html#_dv_duration_class[DV_DURATION^]` +
 +
__Post_condition__: `Result = time.diff(parent.origin)`
a|Offset of this event from origin, computed as time.diff(parent.origin).

h|*Invariants*
2+a|__Offset_validity1__: `offset /= Void and then offset = time.diff (parent.origin)`
|===
