=== PARTY_RELATIONSHIP Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*PARTY_RELATIONSHIP*

h|*Description*
2+a|A relationship between parties. In BFO terms, a Relational quality, i.e. a Quality that s-depends on the parties of the relation.

h|*Inherit*
2+|`<<_entity_relationship_class,ENTITY_RELATIONSHIP>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*scoper*: `<<_accountability_class,ACCOUNTABILITY>>`
a|The Accountability defining the scope of this relationship; typically a job post.

h|*1..1 +
(redefined)*
|*source*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Source of relationship, may be understood as 'owner' of relationship.

h|*1..1 +
(redefined)*
|*target*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Target of relationship.

h|*Invariants*
2+a|__Target_valid__: `target /= Void and then not target.reverse_relationships.has (self)`

h|
2+a|__Source_valid__: `source /= Void and then source.relationships.has (self)`

h|
2+a|__Type_validity__: `type = name`
|===
