=== PARTY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_PARTY (abstract)_*

h|*Description*
2+a|Ancestor of all Party types, including real world entities and their roles. A Party is any entity which can participate in an activity. The `_name_` attribute inherited from `LOCATABLE` is used to indicate the actual type of party (note that the actual names, i.e. identities of parties are indicated in the `_identities_` attribute, not the `_name_` attribute).

h|*Inherit*
2+|`LOCATABLE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*identities*: `List<PARTY_IDENTITY>`
a|Identities used by the party to identify itself, such as legal name, stage names, aliases, nicknames and so on.

h|*0..1*
|*contacts*: `List<CONTACT>`
a|Contacts for this party.

h|*0..1*
|*details*: `ITEM_STRUCTURE`
a|All other details for this Party.

h|*0..1*
|*reverse_relationships*: `List<LOCATABLE_REF>`
a|References to relationships in which this Party takes part as target.

h|*0..1*
|*relationships*: `List<PARTY_RELATIONSHIP>`
a|Relationships in which this Party takes part as source.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*type* (): `DV_TEXT`
a|Type of party, such as  `PERSON`,  `ORGANISATION`, etc. Role name, e.g.  general practitioner ,  nurse ,  private citizen . Taken from inherited `_name_` attribute.

h|*Invariants*
2+a|*_Type_valid_*: `type = name`

h|
2+a|*_Contacts_valid_*: `contacts /= Void implies not contacts.is_empty`

h|
2+a|*_Relationships_validity_*: `relationships /= Void implies (not relationships.is_empty and then relationships.for_all (r &#124; r.source = self)`

h|
2+a|*_Reverse_relationships_validity_*: `reverse_relationships /= Void implies (not reverse_relationships.empty and then reverse_relationships.for_all (item &#124; repository ("demographics").all_party_relationships.has_object (item) and then repository("demographics").all_party_relationships.object (item).target = self))`

h|
2+a|*_Is_archetype_root_*: `is_archetype_root`
|===
