=== PARTY_IDENTITY Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*PARTY_IDENTITY*

|*Description*
{set:cellbgcolor:lightblue}
2+|An identity  owned  by a PARTY, such as a person name or company name, and which is used by the party to identify itself. Actual structure is archetyped.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|LOCATABLE
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*details*: `ITEM_STRUCTURE`
{set:cellbgcolor!}
|The value of the indentity. This will often taken the form of a parsable string or a small structure of strings.
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*purpose*: `DV_TEXT`
{set:cellbgcolor!}
|Purpose of identity, e.g.  legal ,  stagename ,  nickname ,  tribal name ,  trading name . Taken from value of inherited name attribute.

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Purpose_valid_*: purpose = name
{set:cellbgcolor!}
|===
