=== PARTY_IDENTITY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*PARTY_IDENTITY*

h|*Description*
2+a|An identity  owned  by a PARTY, such as a person name or company name, and which is used by the party to identify itself. Actual structure is archetyped.

h|*Inherit*
2+|`link:/releases/RM/{rm_release}/common.html#_locatable_class[LOCATABLE^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*details*: `link:/releases/RM/{rm_release}/data_structures.html#_item_structure_class[ITEM_STRUCTURE^]`
a|The value of the indentity. This will often taken the form of a parsable string or a small structure of strings.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*purpose* (): `link:/releases/RM/{rm_release}/data_types.html#_dv_text_class[DV_TEXT^]`
a|Purpose of identity, e.g.  legal ,  stagename ,  nickname ,  tribal name ,  trading name . Taken from value of inherited name attribute.

h|*1..1*
|*as_string* (): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Identity in the form of a single string.

h|*Invariants*
2+a|__Purpose_valid__: `purpose = name`
|===
