=== PARTY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__PARTY (abstract)__*

h|*Description*
2+a|Ancestor of all Party types, including real world entities and their roles. A Party is any entity which can participate in an activity. The `_name_` attribute inherited from `LOCATABLE` is used to indicate the actual type of party (note that the actual names, i.e. identities of parties are indicated in the `_identities_` attribute, not the `_name_` attribute).

NOTE: It is strongly recommended that the inherited attribute `_uid_` be populated in `PARTY` objects, using the UID copied from the `_object_id()_` of the `_uid_` field of the enclosing `VERSION` object. +
For example, the `ORIGINAL_VERSION.uid` `87284370-2D4B-4e3d-A3F3-F303D2F4F34B::uk.nhs.ehr1::2`  would be copied to the `_uid_` field of the `PARTY` object.

h|*Inherit*
2+|`link:/releases/RM/{rm_release}/common.html#_locatable_class[LOCATABLE^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*identities*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_party_identity_class,PARTY_IDENTITY>>>`
a|Identities used by the party to identify itself, such as legal name, stage names, aliases, nicknames and so on.

h|*0..1*
|*contacts*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_contact_class,CONTACT>>>`
a|Contacts for this party.

h|*0..1*
|*details*: `link:/releases/RM/{rm_release}/data_structures.html#_item_structure_class[ITEM_STRUCTURE^]`
a|All other details for this Party.

h|*0..1*
|*reverse_relationships*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/base_types.html#_locatable_ref_class[LOCATABLE_REF^]>`
a|References to relationships in which this Party takes part as target.

h|*0..1*
|*relationships*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_party_relationship_class,PARTY_RELATIONSHIP>>>`
a|Relationships in which this Party takes part as source.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*type* (): `link:/releases/RM/{rm_release}/data_types.html#_dv_text_class[DV_TEXT^]`
a|Type of party, such as  `PERSON`,  `ORGANISATION`, etc. Role name, e.g.  general practitioner ,  nurse ,  private citizen . Taken from inherited `_name_` attribute.

h|*Invariants*
2+a|__Type_valid__: `type = name`

h|
2+a|__Contacts_valid__: `contacts /= Void implies not contacts.is_empty`

h|
2+a|__Relationships_validity__: `relationships /= Void implies (not relationships.is_empty and then relationships.for_all (r &#124; r.source = self)`

h|
2+a|__Reverse_relationships_validity__: `reverse_relationships /= Void implies (not reverse_relationships.empty and then reverse_relationships.for_all (item &#124; repository ("demographics").all_party_relationships.has_object (item) and then repository("demographics").all_party_relationships.object (item).target = self))`

h|
2+a|__Is_archetype_root__: `is_archetype_root`

h|
2+a|__Uid_mandatory__: `uid /= Void`
|===
