=== PARTY_RELATIONSHIP Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*PARTY_RELATIONSHIP*

|*Description*
{set:cellbgcolor:lightblue}
2+|Generic description of a relationship between parties.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|LOCATABLE
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*0..1*
{set:cellbgcolor:lightblue}
|*details*: `ITEM_STRUCTURE`
{set:cellbgcolor!}
|The detailed description of the relationship.

|*0..1*
{set:cellbgcolor:lightblue}
|*time_validity*: `DV_INTERVAL<DV_DATE>`
{set:cellbgcolor!}
|Valid time interval for this relationship.

|*1..1*
{set:cellbgcolor:lightblue}
|*source*: `PARTY_REF`
{set:cellbgcolor!}
|Source of relationship.

|*1..1*
{set:cellbgcolor:lightblue}
|*target*: `PARTY_REF`
{set:cellbgcolor!}
|Target of relationship.
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*type*: `DV_TEXT`
{set:cellbgcolor!}
|Type of relationship, such as  employment,  authority,  health provision 

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Source_valid_*: source /= Void and then source.relationships.has (self)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Target_valid_*: target /= Void and then not target.reverse_relationships.has (self)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Type_validity_*: type = name
{set:cellbgcolor!}
|===
