=== REFERENCE_RANGE Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*REFERENCE_RANGE*

|*Description*
{set:cellbgcolor:lightblue}
2+|Defines a named range to be associated with any ORDERED datum. Each such range is particular to the patient and context, e.g. sex, age, and any other factor which affects ranges. May be used to represent normal, therapeutic, dangerous, critical etc ranges.
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*meaning*: `DV_TEXT`
{set:cellbgcolor!}
|Term whose value indicates the meaning of this range, e.g.  normal,  critical,  therapeutic  etc.

|*1..1*
{set:cellbgcolor:lightblue}
|*range*: `DV_INTERVAL`
{set:cellbgcolor!}
|The data range for this meaning, e.g. critical  etc.
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*is_in_range* (v: `DV_ORDERED`): `Boolean`
{set:cellbgcolor!}
|Indicates if the value  val' is inside the range.
|===
