=== TASK_ITEM Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_TASK_ITEM (abstract)_*

h|*Description*
2+a|Abstract parent type of the Task definition types TASK_GROUP and TASK.

Supports definition of optionality, pre-conditions, wait conditions, indications and notifications with any Task Group or Task.

Provides a place to record fine-grained costing data.

Informal other participations can also be recorded for any Task Group or Task, although these do not replace the Task Plan principal_performer.

h|*Inherit*
2+|`PLAN_ITEM`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*other_participations*: `List<TASK_PARTICIPATION>`
a|List of participations for task item.

h|*0..1*
|*costing_data*: `TASK_COSTING`
a|Costing data related to this Task item.

h|*0..1*
|*preconditions*: `List<TASK_PRECONDITION>`
a|Condition which must be met for the TASK_ITEM to be available to perform in a runtime execution context.

h|*0..1*
|*other_details*: `ITEM_STRUCTURE`
a|Archetypable structure for recording non hard-modelled information.

h|*0..1*
|*execution_time*: `TIMING_SPEC`
a|Optional specifier of time at which the Task of Task Group should be performed. If not provided, the Task is assumed to be available to perform immediately following completion of the previous members of the parent Task Group.

The Task may be performed earlier or later than this time; it is understood as a guide only.
|===
