=== TASK_PLAN Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*TASK_PLAN*

h|*Description*
2+a|Logical list of Tasks in a structure defining order and conditions of execution of items of work intended to achieve a goal. A Task Plan consists of a top-level TASK_GROUP containing TASK_PLAN_ITEMs, which are either atomic TASKs or more TASK_GROUPs.

A Task Plan specifies a principal_performer, representing a kind of actor who can perform the Tasks, and bounding start_time and completion_time information.

It has an associated execution_history that can be used to record work events in time.

The attributes care_plan and guideline_id provide a way of associating a Task Plan with an operational care plan, and also a published guideline or protocol on which the Task Plan may be based.

h|*Inherit*
2+|CONTENT_ITEM

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*subject*: `PARTY_PROXY`
a|Optional indicator of subject of Task, which is normally the subject of the EHR. If this is not the case, this attribute states who the Task is to be performed on.

h|*0..1*
|*description*: `DV_TEXT`
a|Human-understandable description of the Task Plan, which may be specific to the work items and patient.

h|*0..1*
|*care_plan*: `LOCATABLE_REF`
a|Care plan object from which this Task Plan is derived.

h|*0..1*
|*guideline*: `DV_IDENTIFIER`
a|Identifier of guideline on which this Task Plan is based, if such exists. A 'guideline' is understood here as a published standard for performing a detailed Task.

It is currently assumed that there is no reliable machine identifier system for guidelines. A DV_IDENTIFIER allows things like:

* issuer = "NICE";
* id = "https://www.nice.org.uk/guidance/cg180"
* type = "NHS guideline for Atrial fibrillation: management"

h|*0..1*
|*principal_performer*: `TASK_PARTICIPATION`
a|Specification of principle performer of this Task Plan as a Participation, typically with role and function set.

h|*0..1*
|*care_pathway*: `DV_IDENTIFIER`
a|Identifier of care pathway etc, on which this Task Plan is based, if such exists. A 'care pathway' is understood here as a published standard for performing care for a major condition or presenting complaint, e.g. sepsis, MI etc.

It is currently assumed that there is no reliable machine identifier system for care pathways. A DV_IDENTIFIER allows things like:

* issuer = "NICE";
* id = "https://pathways.nice.org.uk/pathways/sepsis"
* type = "NICE Sepsis care pathway"

h|*1..1*
|*definition*: `TASK_GROUP`
a|The Tasks for this Task Plan.

h|*0..1*
|*execution_history*: `TASK_PLAN_EXECUTION_HISTORY`
a|History of execution events for an execution of this Task Plan.

h|*0..1*
|*training_level*: `Integer`
a|An integer value representing the training level for which this Task Plan is designed. A high value corresponds to a lower level of expertise. The default value is zero.

h|*0..1*
|*best_practice_ref*: `DV_URI`
a|A URI (typically a local URL) that points to the document form of any governing guideline or other best practice publication in use in the current institution. This link provides a way for a clinician to cross-check the Task List design and functioning against the definitive document that acts as the source of its semantics.

h|*0..1*
|*expiry_time*: `Duration`
a|Maximal date/time by which this Task Plan should be considered obsolete. If not set, the Task Plan would normally be inferred to be obsolete after a discharge from acute care, but in primary or social care situations, no value may be assumed to indicate that the Tasks are still to be performed, depending on the times specified in the execution_time attribute of TASKs in the plan.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*lifecycle_state*: `TASK_LIFECYCLE`
a|Lifecycle state of Task Plan, derived as a copy of the lifecycle_state() of the top-level TASK_GROUP.
|===
