=== TASK_PLAN Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TASK_PLAN*

h|*Description*
2+a|Logical list of Tasks in a structure defining order and conditions of execution of items of work intended to achieve a goal. A Task Plan consists of a top-level TASK_GROUP containing PLAN_ITEMs, which are either atomic TASKs, more TASK_GROUPs or DECISION nodes.

A Task Plan specifies a principal_performer, representing a kind of actor who can perform the Tasks, and bounding start_time and completion_time information.

It has an associated execution_history that can be used to record work events in time.

The attributes care_plan and guideline_id provide a way of associating a Task Plan with an operational care plan, and also a published guideline or protocol on which the Task Plan may be based.

h|*Inherit*
2+|`LOCATABLE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*description*: `DV_TEXT`
a|Human-understandable description of the Task Plan, which may be specific to the work items and patient.

h|*0..1*
|*subject*: `PARTY_PROXY`
a|Optional indicator of subject of Task, which is normally the subject of the EHR. If this is not the case, this attribute states who the Task is to be performed on.

h|*0..1*
|*guideline*: `DV_IDENTIFIER`
a|Identifier of guideline on which this Task Plan is based, if such exists. A 'guideline' is understood here as a published standard for performing a detailed Task.

It is currently assumed that there is no reliable machine identifier system for guidelines. A DV_IDENTIFIER allows things like:

* issuer = "NICE";
* id = "https://www.nice.org.uk/guidance/cg180"
* type = "NHS guideline for Atrial fibrillation: management"

h|*1..1*
|*definition*: `TASK_GROUP`
a|The Tasks for the main part of this Task Plan; this section of the plan may be repeatable.

h|*0..1*
|*execution_history*: `TASK_PLAN_EXECUTION_HISTORY`
a|History of execution events for an execution of this Task Plan.

h|*0..1*
|*best_practice_ref*: `DV_URI`
a|A URI (typically a local URL) that points to the document form of any governing guideline or other best practice publication in use in the current institution. This link provides a way for a clinician to cross-check the Task Plan design and functioning against the definitive document that acts as the source of its semantics.

h|*0..1*
|*expiry_time*: `Duration`
a|Maximal date/time by which this Task Plan should be considered obsolete. If not set, the Task Plan would normally be inferred to be obsolete after a discharge from acute care, but in primary or social care situations, no value may be assumed to indicate that the Tasks are still to be performed, depending on the times specified in the execution_time attribute of TASKs in the plan.

h|*0..1*
|*due_time*: `Duration`
a|Due date/time expressed as an offset, to be converted to a real date/time at activation.

h|*0..1*
|*order_set*: `DV_IDENTIFIER`
a|Optional identifier for an order set, which is understood as a _type_ of order set, e.g. 'R-CHOP-14'.

h|*0..1*
|*workflow_id*: `OBJECT_REF`
a|Identifier of instance of order set from which this Task Plan is drawn, if there is one. Should match the workflow_id in all INSTRUCTION and other ENTRY instances created due to the same order set instance.

TODO: needed?

h|*0..1*
|*context*: `PLAN_DATA_CONTEXT`
a|

h|*0..1*
|*indications*: `List<DV_TEXT>`
a|Clinical applicability of this Task item to subject of work, e.g. 'pregnancy', 'lymphoma' etc. May be derived from a governing guideline. May be displayed as a safety precaution to human performer.
|===
