=== TASK_GROUP Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TASK_GROUP*

h|*Description*
2+a|Grouping structure that defines the execution basis for a collection of Tasks, which may include more Task groups.

The execution_type attribute defines the mode of execution. If not set, sequential execution is assumed.

h|*Inherit*
2+|`TASK_ITEM`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*members*: `List<PLAN_ITEM>`
a|Set of Tasks to perform. Sequencing is either the natural order of the tasks list, or may be controlled by

h|*0..1*
|*execution_type*: `EXECUTION_TYPE`
a|Basis for executing the Task items contained in this Task Group.

h|*0..1*
|*principal_performer*: `TASK_PARTICIPATION`
a|Specification of principle performer of this Task Plan as a Participation, in terms of role and optionally function, mode and specific performer as appropriate.

h|*0..1*
|*repeat_spec*: `TASK_REPEAT`
a|

h|*0..1*
|*training_level*: `Integer`
a|An integer value representing the training level for which this Task Plan is designed. A high value corresponds to a lower level of expertise. The default value is zero.
|===
