include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Editor

* Thomas Beale, Ars Semantica (UK); openEHR Foundation Management Board.

=== Contributors

This specification benefited from wide formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people for their contributions.

* Rong Chen MD, PhD, Cambio Healthcare Systems, Sweden
* Heath Frankel, CTO Ocean Informatics, Australia
* Sam Heard MD, Ocean Informatics, Australia
* Sebastian Iancu, Architect, Code24, Netherlands 
* Dipak Kalra MD, PhD, Professor Health Informatics, CHIME, UCL, UK
* David Lloyd (ret), CHIME, UCL, UK
* Chunlan Ma PhD, MD, Ocean Informatics, Australia
* Zar zar Tun, DSTC, Australia

=== Support

The work reported in this paper has been funded in part by the following organisations:

* University College London - Centre for Health Informatics and Multi-professional Education (CHIME);
* Ocean Informatics; 
* Distributed Systems Technology Centre (DSTC), under the Cooperative Research Centres Program through the Department of the Prime Minister and Cabinet of the Commonwealth Government of Australia.

Special thanks to David Ingram, Emeritus Professor of Health Informatics at UCL, who provided a vision and collegial working environment ever since the days of GEHR (1992).
== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.


:sectnums!:

include::partial$amendment_record.adoc[]
