= Overview

The `rm.data_structures` package contains two packages: the `item_structure` package and
the `history` package. The first describes generic, path-addressable data structures, while the latter
describes a generic notion of linear history, for recording events in past time. The
`data_structures package` is illustrated in the UML diagram below.

[.text-center]
.rm.data_structures Package
image::{uml_diagrams_uri}/RM-data_structures.svg[id=data_structures_package, align="center"]

The `data_structures package` itself contains a single class, `DATA_STRUCTURE`, which is the
ancestor of all openEHR data structures. Its only feature is the function as_hierarchy, which is implemented
by each subtype of `DATA_STRUCTURE`, in order to generate a physical representation of the
structure in CEN EN13606 form. The 13606 form is usually less optimal than the openEHR form, but
is compatible with the less semantically rich standard, and is guaranteed (in theory) to be comprehensible
to other systems which support CEN EN13606 as an interoperability standard.

== Instance Structures

Diagrams of typical instances of the structures are included throughout this document. Each instance
of shown in both physical and logical form. The physical form shows the instances which will occur
in data if the structure is implemented using the representation package. The logical form shows
the same instance in a logical form only - i.e. hiding the physical implementation. Only the latter form
is used in other openEHR documents. In all instance diagrams, the following shorthand is used for
well-known attribute names:

* "m = xxxx" - means "meaning = xxxx", i.e. the meaning of the `_archetype_node_id_` attribute inherited from the `LOCATABLE` class.
* "n = xxxx" - means "name = xxxx", i.e. the value of the `_name_` attribute inherited from the `LOCATABLE` class.
* "v = xxxx" - means "value = xxxx", i.e. the value of the `_value_` attribute from the `ELEMENT` class.

== Class Descriptions

include::{uml_export_dir}/classes/data_structure.adoc[]
