= Scenarios

== Protocol-driven Plan

The following UML instance diagram shows a partial state of an EHR containing orders and a related Task List. The upper part shows a `COMPOSITION` containing a number of `INSTRUCTIONs` that express the orders for Cyclophosphamide, Hydroxydaunorubicin (Doxorubicin), etc, that make up the order set for a CHOP chemotherapy protocol (to be more complete, Rituximab would also be included). It is assumed that the orders contain the correct dosages for the patient, i.e. that they have been calculated in advance for the patient's body weight, surface area and other specifics. A few elements of an `ACTIVITY` for the Cyclophosphamide drug are shown here.

In the lower part of the part of the diagram is a `COMPOSITION` containing a `TASK_LIST` structure representing the list of work items to perform in order to administer the chemotherapy to the patient. It is assumed that a specialised chemotherapy application has been used to created this structure. The first `PLANNED_ACTION` is shown in some detail, and includes a reference back to the related Instruction Activity, enabling an application to retrieve and display the details of the order. As a precaution, it also has the `_narrative_` attribute set to the value `"Cyclophosphamide 1400 mg IV"`, copied (or generated) from the `INSTRUCTION` when the `TASK_LIST` was created. The other attributes of the `PLANNED_ACTION` object indicate when to execute the Task, what professional role should do it (`_participations_`), the Careflow step ('administer') and the target state machine state (`active`).

Each of the `PLANNED_TASK` instances in the `TASK_LIST` should logically speaking be almost a copy of the `ACTION` that would result from executing the Task. This is not literally true, since there are fields representing various kinds of links, identifiers and other protocol and care plan information, but for the core information of what to do, and when to do it the instance data for a Planned action should be a tight constraint version of the intended Action to result.

[.text-center]
.Typical Task List - CHOP Chemotherapy
image::{uml_export_dir}/diagrams/Planning-typical-instance.svg[id=planning_typical_instance, align="center"]

It is worth considering some of the differences between how an order represents the Task and how it may be represented in a `PLANNED_ACTION` and an eventual `ACTION`. Consider the fourth drug in the CHOP regimen, a choice of Prednisone or Prednisolone. In the form expressed in the order, i.e. the `INSTRUCTION`, it may be expressed in the following form:

* administer 80mg orally every day for 5 days

This could be expressed as a single `ACTIVITY` with the `INSTRUCTION._tming_` attribute set to represent 'once a day for 5 days'.

In the `TASK_LIST` however, it will be expressed as 5 separate `PLANNED_ACTIONs`, each indicating a single dose for one day. This corresponds to how the drug is actually administered and enables the system (and openEHR data) to represent each action individually, as well as deviations such as not performing one or more of the administrations. The information displayed representing each Task to the human agent will therefore be somewhat different to the form in which it is expressed in the generating order.

However, the order `INSTRUCTION` could have been created using a series of 5 `ACTIVITY` objects each representing a single day's administration. In this case, the form defined in each `ACTIVITY` is very close to the form required to represent each Task in the Task list.

It is assumed that determining how to populate the details of the `PLANNED_ACTIONs` is up to an intelligent application that knows the relationship between the relevant orders or order sets, and the exact form of Task lists to implement them.

== Check-list and Sign-off

[.tbd]
TBD

== Changes during Execution

[.tbd]
TBD

== Abandonment

[.tbd]
TBD
