= Relationship with other openEHR EHR Artefacts

== Principles

The model enables a flexible relationship between a Task List and orders, i.e. openEHR `INSTRUCTIONs`. In simple cases, a Task List will just be the list of Tasks to fulfill one order, i.e. a single `INSTRUCTION`, such as a prescription for a course of antibiotics. The general case however is that the Task List corresponds to a clinical goal which implicates multiple orders, for example the CHOP chemotherapy mentioned above. 

It may also be the case that _not every Task is associated with an order_. While a typical case is that a Task corresponds to an openEHR `ACTION` that has not yet been recorded (and which normally has a driving `INSTRUCTION`), it may also correspond to an `ACTION` that has no `INSTRUCTION` or indeed an `OBSERVATION` or possibly an `EVALUATION` (perhaps some kind of check during a procedure). There is also no reason why a Task List cannot consist of Tasks that define administrative work and would be documented with openEHR `ADMIN_ENTRYs`.

We can infer from the above that the main driver of a Task List isn't in general an order, but a guideline or protocol which usually includes orders. In simple cases, no formal protocol is used, and the orders (i.e. `INSTRUCTIONs`) may be _de facto_ drivers, or the Task List may be created _ad hoc_, such an in-patient pain medication administration plan by nursing staff. At the other extreme, a Task List may be created with no corresponding orders (and therefore no `INSTRUCTIONs`) at all.

The following figure shows the correspondences between the various type of openEHR artefact for the general case of Task Lists. The arrows indicate causal relationships.

[.text-center]
.openEHR Planning Artefact Relationships
image::diagrams/planning_artefacts.svg[id=planning_artefact_relationships, align="center", width=50%]

In the above, items in yellow are driven solely by the guideline and have no corresponding order; planned items with a red cross have been cancelled and have no corresponding performed Action or Observation.

One of the side-effects of distinct state machines for `INSTRUCTIONs` and Task Lists is that not all careflow steps and states in the former need to be represented as Tasks in a Task List. For example, a significant number of careflow steps defined in `ACTION` archetypes are for non-Active states, i.e. Planning, Postponement, Suspension etc. These steps do not need to have Tasks defined for them, since by definition they are nearly all unplanned. 

As a consequence, most Tasks in a Task List correspond only to Active-state careflow steps of constituent order `INSTRUCTIONs`.

== Execution-time EHR Structures

The model described here provides significant power when used with openEHR Instructions, Actions and Observations to represent clinical work driven by guidelines and order sets. This section describes the relationship of information instances that correspond to the various phases of work described earlier, as follows:

* _ordering_: creation of `INSTRUCTIONs`;
* _task planning_: creation of `TASK_LIST(s)` representing a plan of individual tasks that achieve the order intention;
* _execution_: creation of `ACTION` and other Entry types that document the Tasks as they were performed.

The model supports logical linking between these items to support workflow traceability. The following figure illustrates both aspects, which are further described below.

[.text-center]
.Runtime planning structures
image::diagrams/planning_runtime_structures.svg[id=runtime_planning_structures, align="center", width=80%]

Various links can be recorded at execution time, as follows:

* *planned Task to Order reference*: the `TASK_EVENT_RECORD.entry_instances` attribute is used to record reverse reference(s) from a `TASK` to an `ACTIVITY` within an `INSTRUCTION` that records a corresponding order, if one exists (shown on the diagram as a logical link from `DEFINED_TASK` to `ACTIVITY` instances);
* *planned Task to performed Task reference*: the `TASK_EVENT_RECORD.entry_instances` attribute is used to record a forward reference to the Entry instance that was created when this Task was performed, i.e. some `ACTION`, `OBSERVATION` etc (shown on the diagram as a logical link from `DEFINED_TASK` to `ACTION` instances);
* *performed Task to planned Task reference*: the `ENTRY._workflow_id_` attribute may be used to record a reverse reference from an `ACTION`, `OBSERVATION` etc to a causing `TASK` instance.
