= Background

== Functional Needs

The Entry model described in the {openehr_rm_ehr}[openEHR EHR IM] defines a way to record clinical statements representing real observations, decisions, orders and actions that have occurred, in the EHR. In this scheme, Instructions represent orders for certain kinds of Actions to be performed. Actions and Observations represent events that have subsequently occurred in the real world - a real drug administration or an actual blood sugar measurement. 

There is however a common additional need to concretely plan individual Actions and sometimes Observations ahead of time, as a set of 'tasks'. The general concept is usually known as a _task list_, and is used to concretely specify actions to be performed by actors (usually human, but potentially machine as well) providing care.

A list of planned tasks need not all relate to a single order, or indeed any order. The general picture is that a task list corresponds to some self-standing healthcare job to be done, which may include tasks designed to fulfill multiple orders, and also tasks not defined by orders.

To meet this need, a further kind of content can be recorded in the EHR, representing task lists containing tasks. Here we understand the word 'task' to mean 'definition of a planned task', i.e. a description of something to be performed in the future. 

The model described here considers task lists as the lower part of an overall information architecture that includes entities at multiple cognitive levels, i.e.:

* care pathway - a model of a guideline for care of a condition / ideal patient;
* care plan - a general plan for care of an actual patient, taking into account zero or more Care Pathways and individual specificities;
* task list - a concrete concept that defines a list of fine-grained planned tasks to perform over time to achieve a particular goal.

The model described here does not address the representation of the care pathway or care plan levels, only the task list level. It does however assume that a task list may be created due to a care plan of some kind, and that the care plan may in turn have been derived from one or more care pathways or guidelines; accordingly, the means to identify the plan and pathway / guideline are provided.

In the following, the term 'task' thus denotes the definition of an action to be performed, and is normally documented in openEHR by the `ACTION` Entry subtype. However, 'task' is also understood more generally, so that it may also when performed, result in an openEHR `OBSERVATION` or other Entry subtype where appropriate. In the great majority of cases therefore, the term 'task' as it appears here equates to openEHR Actions and Observations.

For the sake of brevity, 'Action' below is intended to imply an openEHR `ACTION`, `OBSRVATION` or potentially other Entry sub-type, unless otherwise stated.

== Execution Paradigm

As soon as the notion of 'planning' is assumed, we enter some form of the workflow space, and it becomes essential to describe the intended paradigm of the human / machine execution environment. This is due to the fact that any description of planned tasks acts as a set of instructions to actors intended to perform the tasks. Since the instructions (task lists) will be represented in the IT layer and the executing actors (generally human, although they may also be devices or software applications) exist in the real world, an account of the interaction between the computing environment and the real world is required.

Although the task list facility described in this specification is relatively simple compared to some workflow tools, we can nevertheless distinguish the following entities in the environment:

* _computing environment_:
** *work plan definition*: a reusable definition of work to be done, consisting of tasks, potentially standardised according to a guideline or protocol;
** *work plan instance*: a run-time instance of a task plan, potentially with local variations, created for execution by an actor or actors;
* _real world_:
** *performing actor*, i.e. a human, machine or software application that performs tasks in the real world as part of a procedure designed to achieve a goal;

In normal environments such as healthcare, the real-world actors are not passive recipients of commands from a computer application implementing a work plan, but are instead active agents who normally work together to perform a job. Working together involves peer to peer communication, ordering of tasks and so on. A workflow application provides help by maintaining a representation of the work plan, and a representation of its progress in execution. It is immediately apparent that the application's idea of a given work plan execution and the real world state of the same work are not identical, and in fact may be only approximately related. For example, the computable form of the work plan might only include some of the tasks and actors at work in the real world. There are in fact two workflows executing: a virtual workflow and the real world one, and there is accordingly a problem of _synchronisation_ of the two.

There is also a question of communication between the workflow application and the real world actors, which we can think of as consisting of:

* *commands*: signals from the work plan system to a real world actor to do something;
* *notifications*: signals to and from the work plan system and the real world actors on the status of work, e.g. 'new work item', 'item completed' etc;
* *data*: data collection from actors and presentation to actors from the system.

This environment can be illustrated as follows.

[.text-center]
.Work plan execution paradigm
image::diagrams/workflow_execution_paradigm.svg[id=workflow_execution_paradigm, align="center", width=60%]
