= Task Planning Model

== Overview

The following UML diagram shows the `rm.task_planning` package in overview form, with the essential classes, inheritance and compositional relationships. The class `WORK_PLAN` is a descendant of `CONTENT_ITEM`, which makes it a type of content that may occur in a `COMPOSITION`. Compositions used for this purpose have their `_category_` attribute set to the openEHR coded term `|Task Plan|`. This enables Task Plans to be committed to the openEHR EHR if desired.

A `WORK_PLAN` is the outermost container for one or more `TASK_PLANs` that refer to each other in some way, as well as the meta-data documenting the plan.

Structurally, a `TASK_PLAN` has a `_definition_` (blue and green classes) consisting of various kinds of `TASK`. Individual Tasks that are `DEFINED_TASKs` (i.e. not references) may have a `_prototype_` whose type is an Entry descendant, that defines the Task data. The prototype is a partly-defined Entry that will be cloned and populated at runtime when/if the Task is completed.

At clinical execution time, the materialsed form of the Plan is represented by `M_XXX` classes, which are instantiated when the plan is activated (central orange classes).

A `TASK_PLAN` may also have an `_execution_history_` (gold classes at bottom), which acts as a record of events that have occurred to the Task Plan during execution.

[.text-center]
.rm.task_planning package overview
image::{uml_export_dir}/diagrams/RM-task_planning-overview.svg[id=rm_task_planning_overview, align="center"]

The key structural relationships are shown in the following instance diagram. On the left is a Task Plan definition, consisting of a Task Group and various Defined Tasks. Each of these Tasks may have a prototype Entry attached, which represents the intended data of an Action, Observation or other Entry that the Task defines.

In the centre is a materialised Task Plan, which is an execution-time structure used to maintain state for an executing Plan (achieved by the `M_PLAN_ITEM._definition_` association). This structure allows the recording of all state to do with Task execution, including instances of variables, timing information and so on. The materialised structure is not owned by the definition structure, but rather is created at run time, and points back to its definition (_owner_ and _definition_ links). The right hand side shows a part of the materialised structure that is currently instantiated within a user-application session.

At the lower right is a Task Execution History, which is a record of all events that were made during the execution of the original Task Plan.

[.text-center]
.Task planning overview
image::diagrams/task_planning_overview.svg[id=task_planning_overview, align="center", width=90%]

== Class Descriptions

The following classes are common to all sub-packages.

include::{uml_export_dir}/classes/task_lifecycle.adoc[]

include::{uml_export_dir}/classes/system_call.adoc[]

include::{uml_export_dir}/classes/callback_type.adoc[]
