//
// ============================================ Asciidoc HEADER =============================================
//

//
// ============================================ Asciidoc PREAMBLE =============================================
//


= {spec_title}


//
// ============================================= Asciidoc BODY ===============================================
//


//
// --------------------------------------------- Preface -----------------------------------------------
//
== Acknowledgements

The work reported in this paper has been funded in by the following organisations:

* University College London - Centre for Health Informatics and Multi-professional Education (CHIME);
* Ocean Informatics; 
* Distributed Systems Technology Centre (DSTC), under the Cooperative Research Centres Program through the Department of the Prime Minister and Cabinet of the Commonwealth Government of Australia.

Thanks to Grahame Grieve of Kestral Computing, Australia for general input and examples relating to History data.

Special thanks to David Ingram, Emeritus Professor of Health Informatics at UCL, who provided a vision and collegial working environment ever since the days of GEHR (1992).

//
// --------------------------------------------- TOC -----------------------------------------------
//
//toc::[left]

//
// --------------------------------------------- CHAPTERS -----------------------------------------------
//

//
// --------------------------------------------- REFERENCES -----------------------------------------------
//
:sectnums!:
== References
bibliography::[]
