== Component RM

=== Model org.openehr.rm

==== Package common

http://www.openehr.org/releases/RM/latest/common.html#_archetyped_class[Class ARCHETYPED]

http://www.openehr.org/releases/RM/latest/common.html#_attestation_class[Class ATTESTATION]

http://www.openehr.org/releases/RM/latest/common.html#_audit_details_class[Class AUDIT_DETAILS]

http://www.openehr.org/releases/RM/latest/common.html#_authored_resource_class[Class AUTHORED_RESOURCE]

http://www.openehr.org/releases/RM/latest/common.html#_contribution_class[Class CONTRIBUTION]

http://www.openehr.org/releases/RM/latest/common.html#_feeder_audit_class[Class FEEDER_AUDIT]

http://www.openehr.org/releases/RM/latest/common.html#_feeder_audit_details_class[Class FEEDER_AUDIT_DETAILS]

http://www.openehr.org/releases/RM/latest/common.html#_folder_class[Class FOLDER]

http://www.openehr.org/releases/RM/latest/common.html#_imported_version_class[Class IMPORTED_VERSION]

http://www.openehr.org/releases/RM/latest/common.html#_link_class[Class LINK]

http://www.openehr.org/releases/RM/latest/common.html#_locatable_class[Class LOCATABLE]

http://www.openehr.org/releases/RM/latest/common.html#_original_version_class[Class ORIGINAL_VERSION]

http://www.openehr.org/releases/RM/latest/common.html#_participation_class[Class PARTICIPATION]

http://www.openehr.org/releases/RM/latest/common.html#_party_identified_class[Class PARTY_IDENTIFIED]

http://www.openehr.org/releases/RM/latest/common.html#_party_proxy_class[Class PARTY_PROXY]

http://www.openehr.org/releases/RM/latest/common.html#_party_related_class[Class PARTY_RELATED]

http://www.openehr.org/releases/RM/latest/common.html#_party_self_class[Class PARTY_SELF]

http://www.openehr.org/releases/RM/latest/common.html#_pathable_class[Class PATHABLE]

http://www.openehr.org/releases/RM/latest/common.html#_resource_description_class[Class RESOURCE_DESCRIPTION]

http://www.openehr.org/releases/RM/latest/common.html#_resource_description_item_class[Class RESOURCE_DESCRIPTION_ITEM]

http://www.openehr.org/releases/RM/latest/common.html#_revision_history_class[Class REVISION_HISTORY]

http://www.openehr.org/releases/RM/latest/common.html#_revision_history_item_class[Class REVISION_HISTORY_ITEM]

http://www.openehr.org/releases/RM/latest/common.html#_translation_details_class[Class TRANSLATION_DETAILS]

http://www.openehr.org/releases/RM/latest/common.html#_version_class[Class VERSION]

http://www.openehr.org/releases/RM/latest/common.html#_versioned_folder_class[Class VERSIONED_FOLDER]

http://www.openehr.org/releases/RM/latest/common.html#_versioned_object_class[Class VERSIONED_OBJECT]

==== Package composition

http://www.openehr.org/releases/RM/latest/composition.html#_action_class[Class ACTION]

http://www.openehr.org/releases/RM/latest/composition.html#_activity_class[Class ACTIVITY]

http://www.openehr.org/releases/RM/latest/composition.html#_admin_entry_class[Class ADMIN_ENTRY]

http://www.openehr.org/releases/RM/latest/composition.html#_care_entry_class[Class CARE_ENTRY]

http://www.openehr.org/releases/RM/latest/composition.html#_composition_class[Class COMPOSITION]

http://www.openehr.org/releases/RM/latest/composition.html#_content_item_class[Class CONTENT_ITEM]

http://www.openehr.org/releases/RM/latest/composition.html#_entry_class[Class ENTRY]

http://www.openehr.org/releases/RM/latest/composition.html#_evaluation_class[Class EVALUATION]

http://www.openehr.org/releases/RM/latest/composition.html#_event_context_class[Class EVENT_CONTEXT]

http://www.openehr.org/releases/RM/latest/composition.html#_instruction_class[Class INSTRUCTION]

http://www.openehr.org/releases/RM/latest/composition.html#_instruction_details_class[Class INSTRUCTION_DETAILS]

http://www.openehr.org/releases/RM/latest/composition.html#_ism_transition_class[Class ISM_TRANSITION]

http://www.openehr.org/releases/RM/latest/composition.html#_observation_class[Class OBSERVATION]

http://www.openehr.org/releases/RM/latest/composition.html#_section_class[Class SECTION]

==== Package data_structures

http://www.openehr.org/releases/RM/latest/data_structures.html#_cluster_class[Class CLUSTER]

http://www.openehr.org/releases/RM/latest/data_structures.html#_data_structure_class[Class DATA_STRUCTURE]

http://www.openehr.org/releases/RM/latest/data_structures.html#_element_class[Class ELEMENT]

http://www.openehr.org/releases/RM/latest/data_structures.html#_event_class[Class EVENT]

http://www.openehr.org/releases/RM/latest/data_structures.html#_history_class[Class HISTORY]

http://www.openehr.org/releases/RM/latest/data_structures.html#_history<item_structure>_class[Class HISTORY<ITEM_STRUCTURE>]

http://www.openehr.org/releases/RM/latest/data_structures.html#_interval_event_class[Class INTERVAL_EVENT]

http://www.openehr.org/releases/RM/latest/data_structures.html#_item_class[Class ITEM]

http://www.openehr.org/releases/RM/latest/data_structures.html#_item_list_class[Class ITEM_LIST]

http://www.openehr.org/releases/RM/latest/data_structures.html#_item_single_class[Class ITEM_SINGLE]

http://www.openehr.org/releases/RM/latest/data_structures.html#_item_structure_class[Class ITEM_STRUCTURE]

http://www.openehr.org/releases/RM/latest/data_structures.html#_item_table_class[Class ITEM_TABLE]

http://www.openehr.org/releases/RM/latest/data_structures.html#_item_tree_class[Class ITEM_TREE]

http://www.openehr.org/releases/RM/latest/data_structures.html#_point_event_class[Class POINT_EVENT]

==== Package data_types

http://www.openehr.org/releases/RM/latest/data_types.html#_code_phrase_class[Class CODE_PHRASE]

http://www.openehr.org/releases/RM/latest/data_types.html#_data_value_class[Class DATA_VALUE]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_absolute_quantity_class[Class DV_ABSOLUTE_QUANTITY]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_amount_class[Class DV_AMOUNT]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_boolean_class[Class DV_BOOLEAN]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_coded_text_class[Class DV_CODED_TEXT]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_count_class[Class DV_COUNT]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_date_class[Class DV_DATE]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_date_time_class[Class DV_DATE_TIME]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_duration_class[Class DV_DURATION]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_ehr_uri_class[Class DV_EHR_URI]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_encapsulated_class[Class DV_ENCAPSULATED]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_general_time_specification_class[Class DV_GENERAL_TIME_SPECIFICATION]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_identifier_class[Class DV_IDENTIFIER]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_interval_class[Class DV_INTERVAL]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_interval<dv_count>_class[Class DV_INTERVAL<DV_COUNT>]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_interval<dv_date>_class[Class DV_INTERVAL<DV_DATE>]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_interval<dv_date_time>_class[Class DV_INTERVAL<DV_DATE_TIME>]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_interval<dv_proportion>_class[Class DV_INTERVAL<DV_PROPORTION>]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_interval<dv_quantity>_class[Class DV_INTERVAL<DV_QUANTITY>]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_multimedia_class[Class DV_MULTIMEDIA]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_ordered_class[Class DV_ORDERED]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_ordinal_class[Class DV_ORDINAL]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_paragraph_class[Class DV_PARAGRAPH]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_parsable_class[Class DV_PARSABLE]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_periodic_time_specification_class[Class DV_PERIODIC_TIME_SPECIFICATION]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_proportion_class[Class DV_PROPORTION]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_quantified_class[Class DV_QUANTIFIED]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_quantity_class[Class DV_QUANTITY]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_state_class[Class DV_STATE]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_temporal_class[Class DV_TEMPORAL]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_text_class[Class DV_TEXT]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_time_class[Class DV_TIME]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_time_specification_class[Class DV_TIME_SPECIFICATION]

http://www.openehr.org/releases/RM/latest/data_types.html#_dv_uri_class[Class DV_URI]

http://www.openehr.org/releases/RM/latest/data_types.html#_proportion_kind_class[Class PROPORTION_KIND]

http://www.openehr.org/releases/RM/latest/data_types.html#_reference_range_class[Class REFERENCE_RANGE]

http://www.openehr.org/releases/RM/latest/data_types.html#_reference_range<dv_count>_class[Class REFERENCE_RANGE<DV_COUNT>]

http://www.openehr.org/releases/RM/latest/data_types.html#_reference_range<dv_proportion>_class[Class REFERENCE_RANGE<DV_PROPORTION>]

http://www.openehr.org/releases/RM/latest/data_types.html#_reference_range<dv_quantity>_class[Class REFERENCE_RANGE<DV_QUANTITY>]

http://www.openehr.org/releases/RM/latest/data_types.html#_term_mapping_class[Class TERM_MAPPING]

==== Package demographic

http://www.openehr.org/releases/RM/latest/demographic.html#_actor_class[Class ACTOR]

http://www.openehr.org/releases/RM/latest/demographic.html#_address_class[Class ADDRESS]

http://www.openehr.org/releases/RM/latest/demographic.html#_agent_class[Class AGENT]

http://www.openehr.org/releases/RM/latest/demographic.html#_capability_class[Class CAPABILITY]

http://www.openehr.org/releases/RM/latest/demographic.html#_contact_class[Class CONTACT]

http://www.openehr.org/releases/RM/latest/demographic.html#_group_class[Class GROUP]

http://www.openehr.org/releases/RM/latest/demographic.html#_organisation_class[Class ORGANISATION]

http://www.openehr.org/releases/RM/latest/demographic.html#_party_class[Class PARTY]

http://www.openehr.org/releases/RM/latest/demographic.html#_party_identity_class[Class PARTY_IDENTITY]

http://www.openehr.org/releases/RM/latest/demographic.html#_party_relationship_class[Class PARTY_RELATIONSHIP]

http://www.openehr.org/releases/RM/latest/demographic.html#_person_class[Class PERSON]

http://www.openehr.org/releases/RM/latest/demographic.html#_role_class[Class ROLE]

http://www.openehr.org/releases/RM/latest/demographic.html#_versioned_party_class[Class VERSIONED_PARTY]

==== Package ehr

http://www.openehr.org/releases/RM/latest/ehr.html#_ehr_class[Class EHR]

http://www.openehr.org/releases/RM/latest/ehr.html#_ehr_access_class[Class EHR_ACCESS]

http://www.openehr.org/releases/RM/latest/ehr.html#_ehr_status_class[Class EHR_STATUS]

http://www.openehr.org/releases/RM/latest/ehr.html#_versioned_composition_class[Class VERSIONED_COMPOSITION]

http://www.openehr.org/releases/RM/latest/ehr.html#_versioned_ehr_access_class[Class VERSIONED_EHR_ACCESS]

http://www.openehr.org/releases/RM/latest/ehr.html#_versioned_ehr_status_class[Class VERSIONED_EHR_STATUS]

==== Package ehr_extract

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_addressed_message_class[Class ADDRESSED_MESSAGE]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_class[Class EXTRACT]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_action_request_class[Class EXTRACT_ACTION_REQUEST]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_chapter_class[Class EXTRACT_CHAPTER]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_content_item_class[Class EXTRACT_CONTENT_ITEM]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_entity_chapter_class[Class EXTRACT_ENTITY_CHAPTER]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_entity_manifest_class[Class EXTRACT_ENTITY_MANIFEST]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_error_class[Class EXTRACT_ERROR]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_folder_class[Class EXTRACT_FOLDER]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_item_class[Class EXTRACT_ITEM]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_manifest_class[Class EXTRACT_MANIFEST]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_participation_class[Class EXTRACT_PARTICIPATION]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_request_class[Class EXTRACT_REQUEST]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_spec_class[Class EXTRACT_SPEC]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_update_spec_class[Class EXTRACT_UPDATE_SPEC]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_extract_version_spec_class[Class EXTRACT_VERSION_SPEC]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_generic_content_item_class[Class GENERIC_CONTENT_ITEM]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_message_class[Class MESSAGE]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_message_content_class[Class MESSAGE_CONTENT]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_openehr_content_item_class[Class OPENEHR_CONTENT_ITEM]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_sync_extract_class[Class SYNC_EXTRACT]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_sync_extract_request_class[Class SYNC_EXTRACT_REQUEST]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_sync_extract_spec_class[Class SYNC_EXTRACT_SPEC]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_x_contribution_class[Class X_CONTRIBUTION]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_x_versioned_composition_class[Class X_VERSIONED_COMPOSITION]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_x_versioned_ehr_access_class[Class X_VERSIONED_EHR_ACCESS]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_x_versioned_ehr_status_class[Class X_VERSIONED_EHR_STATUS]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_x_versioned_folder_class[Class X_VERSIONED_FOLDER]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_x_versioned_object_class[Class X_VERSIONED_OBJECT]

http://www.openehr.org/releases/RM/latest/ehr_extract.html#_x_versioned_party_class[Class X_VERSIONED_PARTY]

==== Package integration

http://www.openehr.org/releases/RM/latest/integration.html#_generic_entry_class[Class GENERIC_ENTRY]

==== Package security

http://www.openehr.org/releases/RM/latest/security.html#_access_control_settings_class[Class ACCESS_CONTROL_SETTINGS]

==== Package support

http://www.openehr.org/releases/RM/latest/support.html#_access_group_ref_class[Class ACCESS_GROUP_REF]

http://www.openehr.org/releases/RM/latest/support.html#_archetype_id_class[Class ARCHETYPE_ID]

http://www.openehr.org/releases/RM/latest/support.html#_basic_definitions_class[Class BASIC_DEFINITIONS]

http://www.openehr.org/releases/RM/latest/support.html#_code_set_access_interface[Interface CODE_SET_ACCESS]

http://www.openehr.org/releases/RM/latest/support.html#_external_environment_access_class[Class EXTERNAL_ENVIRONMENT_ACCESS]

http://www.openehr.org/releases/RM/latest/support.html#_generic_id_class[Class GENERIC_ID]

http://www.openehr.org/releases/RM/latest/support.html#_hier_object_id_class[Class HIER_OBJECT_ID]

http://www.openehr.org/releases/RM/latest/support.html#_internet_id_class[Class INTERNET_ID]

http://www.openehr.org/releases/RM/latest/support.html#_iso_oid_class[Class ISO_OID]

http://www.openehr.org/releases/RM/latest/support.html#_locatable_ref_class[Class LOCATABLE_REF]

http://www.openehr.org/releases/RM/latest/support.html#_measurement_service_class[Class MEASUREMENT_SERVICE]

http://www.openehr.org/releases/RM/latest/support.html#_object_id_class[Class OBJECT_ID]

http://www.openehr.org/releases/RM/latest/support.html#_object_ref_class[Class OBJECT_REF]

http://www.openehr.org/releases/RM/latest/support.html#_object_version_id_class[Class OBJECT_VERSION_ID]

http://www.openehr.org/releases/RM/latest/support.html#_openehr_code_set_identifiers_class[Class OPENEHR_CODE_SET_IDENTIFIERS]

http://www.openehr.org/releases/RM/latest/support.html#_openehr_definitions_class[Class OPENEHR_DEFINITIONS]

http://www.openehr.org/releases/RM/latest/support.html#_openehr_terminology_group_identifiers_class[Class OPENEHR_TERMINOLOGY_GROUP_IDENTIFIERS]

http://www.openehr.org/releases/RM/latest/support.html#_party_ref_class[Class PARTY_REF]

http://www.openehr.org/releases/RM/latest/support.html#_template_id_class[Class TEMPLATE_ID]

http://www.openehr.org/releases/RM/latest/support.html#_terminology_access_interface[Interface TERMINOLOGY_ACCESS]

http://www.openehr.org/releases/RM/latest/support.html#_terminology_id_class[Class TERMINOLOGY_ID]

http://www.openehr.org/releases/RM/latest/support.html#_terminology_service_class[Class TERMINOLOGY_SERVICE]

http://www.openehr.org/releases/RM/latest/support.html#_uid_class[Class UID]

http://www.openehr.org/releases/RM/latest/support.html#_uid_based_id_class[Class UID_BASED_ID]

http://www.openehr.org/releases/RM/latest/support.html#_uuid_class[Class UUID]

http://www.openehr.org/releases/RM/latest/support.html#_version_tree_id_class[Class VERSION_TREE_ID]

