= Preface

== Purpose

This document defines the openEHR Data Types This document describes the architecture of the openEHR EHR Extract Information Model. This
model formally defines the concepts of ‘extract request’, ‘extract’, various kinds of content including
openEHR and non-openEHR, and a message wrapper. It covers use cases including EHR system
communication, other clinical content messaging, and EHR system synchronisation, as well as providing
an equivalent of the ISO 13606 EHR Extract. Model, used throughout the openEHR Reference Model.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.
* Health data managers.

== Related Documents

Prerequisite documents for reading this document include:

* The openEHR Architecture Overview (<<openehr_overview>>);
* The openEHR EHR Information Model (<<openehr_ehr_rm>>);

== Status

This specification is in the {spec_status} state. The development version of this document can be found at http://www.openehr.org/releases/RM/latest/ehr_extract.html.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Conformance

Conformance of a data or software artifact to an openEHR Reference Model specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal, automated derivations from the Reference Model, ITS conformance indicates RM conformance.

