= Date Time Package

== Overview

The `data_types.quantity.date_time` package includes three absolute date/time concepts:
`DV_DATE`, `DV_TIME`, `DV_DATE_TIME`, and a relative concept: `DV_DURATION`. The representations of
all of these are {iso_8601}[ISO 8601:2004] compatible date/time strings. They also include the ISO 8601 semantics
for partial dates and times. The `quantity.date_time` package is illustrated below.

[.text-center]
.rm.data_types.quantity.date_time package
image::{uml_diagrams_uri}/RM-data_types.quantity.date_time.svg[id=rm_data_types_quantity_date_time, align="center"]

=== Requirements

==== Standard Date/Times

The basic requirement is for types which represent the following concepts.

* _Date_: a type which records year, month and day in month. Examples include date of birth, date of onset of a problem.
* _Time_: a type which records hour, minute, second, and timezone. Examples include time of meal, time of day when a problem recurs. Timezone is required in a shared EHR repository so that times of clinical events which occurred in different timezones are comparable; this includes specialised pathology tests which might be done in another country.
* _Date_time_: a type which records year, month, day, hour, minute, second, and timezone. Examples include date & time of death, timestamp of any observation. Timezone is required for the same reason as in Time.
* _Duration_: a type which records duration of an event or (in)activity, as days, hours, minutes, and seconds. A duration is understood as being relative to an unstated origin point (such as birth), and may take a negative value, indicating prior to the origin.

==== Partial Date/Times

Partial or uncertain date/times have to be supported in clinical medicine. It is common for patients to
be unsure about dates and durations. Requirements for partial date/times include the following.

* For dates, one of the following rules applies to any instance:
** only the year is known
** only the year and month are known
** If not even the year is known, then the date is obviously extremely approximate and it would
probably be unsafe to represent it computationally. However, if computatable representation
was needed in this case, a date interval can be used. A pedantic example which breaks these
rules is someone who claims to be born on "a Monday at the start of May in 1934" (i.e. day
but not date unknown). Either the clinician determines what date the first Monday in May
1934 actually was and record that (assuming the patient's way of accurately remembering
just happens to be via day rather than date), or else records a partial date of the form "May
1934" (in ISO 8601 form, `"1934-05"`) if they determine that the patient really is unsure.
* Sometimes incomplete times are recorded, which follow the same rule that either the hours
or both the hours and minutes are present. Examples:
** recordings by instruments which only generate hh:mm values (i.e. no seconds);
** recordings by patients who report approximate times of events;
** recordings by clinicians who use approximate times in administrations, e.g. "take insulin at 8am" really means something like 8 am +/- 30 mins.
* Imprecise durations such as '2 - 3 hrs' need to be recordable in a computable form.

To satisfy the faithfulness requirement for health record recording it should always be possible to
record the narrative form of the datum provided by the patient as well as the formal form.

=== Design

==== General Approach

Date/time values are somewhat special in the realm of data types in that they are expressed in their
'customary' form, in which the standard structure of `{value, unit}` and metric relationships between
orders of magnitude do not hold. The customary form is what we are used to using in the social time
domain, such as births, deaths, ages, and times and durations of events which we remember. In all
these cases it is expressed using the familiar year/month/date/hour/minute/second system, in which
the relationships between each successive unit of time is non-metric. The customary form can be converted
to a magnitude since an origin point, and many date/time libraries do this in order to implement
various operations, particularly comparison.

The date/time types fall into two categories: _absolute_ and _relative_. The absolute category comprises
the Date, Date/time and Time concepts, each of which measure time from a known origin. Date and
Date/time measure calendrical time from the date `0001-01-01`, while Time measures clock time from
midnight. Both Date/time and Time can include timezone information, ensuring that their instances
are correctly situated on the same timeline. All absolute time types inherit from the `DV_TEMPORAL`
type, which provides the appropriate signature for the `_diff()_` function.

The relative category contains only the Duration concept, which expresses elapsed time between two
time points. The `DV_DURATION` class is used for expressing durations of clinical phenomena and differences
between absolute times.

With two exceptions, all four concepts conform to the {iso_8601_official}[ISO 8601:2019 standard^], which is accordingly used as the primary definitional basis of the openEHR date/time types. The two exceptions are as follows:

* a negative sign may be used before a Duration, for example '-P10D', meaning '10 days before [origin]', where the 'origin' is a timepoint understood as the origin for the duration;
* the  W' designator may be mixed with other designators. 

The first exception allows the expression of negative durations, indicating an elapsed time prior to an origin point. An example from clinical medicine is the notion of 'adjusted age', whereby the true developmental age of a very premature newborn is computed with respect to the origin point of birth after a nominal gestation period (usually 9 months). A baby born at 6 months would therefore have an adjusted age of '-3 months', or '-P3M' in the format used by the `DV_DURATION` type. The use of the negative enables correctly computed developmental age comparisons of newborns, regardless of prematurity. Negation for ISO 8601 durations is also supported by {w3c_xml_schema}[W3C XML-schema^] and various programming languages.

See the {openehr_foundation_types}#_time_types[Time Types section in the openEHR Foundation Types specification^] for conformance details.

==== Partial Date/Times

The types defined in this specification support the notion of partially specified dates and times. The
modelling approach used here takes into account the known needs for representing partial date/time
data, while balancing that with the need to avoid incomprehensibly complex types whose generality
would only apply to a tiny percent of difficult cases. Thus, the basis for modelling incomplete
date/times is as follows.

* The modelling problem relates only to date/time quantities that need to be computable. For extremely imprecise date/times, if the clinician feels the need, she can record it as narrative text.
* For imprecise durations, an interval should be used, i.e. `DV_INTERVAL<DV_DURATION>`. In this way durations like '2 - 3 hrs' can be represented, and still be computable.

Based on the above considerations, the requirements for partial types are satisfied by the semantics of
ISO 8601:2004 for 'reduced accuracy' date/times, in which parts of a date, time or date/time can be
missing from the right hand end of the string. This models the reasonable situation where e.g. day
may be unknown in a date, but a date cannot have month unknown and day known.

==== Calendars

A comment on calendars is in order. In this specification, all date/time types currently modelled are
Gregorian calendar based. This is the same assumption made by ISO 8601, and most technical
computing systems today in many parts of the world. At first glance this may seem like a culturally
insensitive approach, but in fact it makes sense in computational terms, for both users of the Gregorian and other calendars, e.g. Julian, Islamic, Baha'i, etc. Arguments against trying to use the
date/time classes defined here to represent date/times from any calendar include the following:

* Almost all dates on computer systems, including in regions such as the Indian sub-continent,
Turkey and the middle east, where alternate calendars are in use, are in the Gregorian system.
This is likely to be the case for some time, and may always be the case, regardless of
the continued use of other calendars for religious or other purposes (outside of health);
* If a calendar indicator were used in date quantities, all software, to be correct, would have to
check the value to verify that it is in the expected calendar system, and to do something special
if it is not - an added cost which is a possible source of bugs and which would rarely be
used. The reality is that most software produced in the western world, India etc (possibly
excepting open source software) would automatically assume the Gregorian calendar, and
would be in error if ever it did receive EHR data containing dates from alternate calendars.
* If/when other calendars are used in EHR or related systems, the users of those calendars will
be aware of it, and include the appropriate conversion logic between Gregorian dates and
their own, limiting the extra software work and quality issues to those users who actually
need alternate calendars. If EHRs from such places are sent to a health care facility where
Gregorian is the default, nothing special is needed to ensure that those records will contain
dates comprehensible to the receiver.
* The detailed model of date/times in some other calendars is not the same as in the Gregorian
calendar, so they would require different classes anyway - the classes defined here would
not necessarily function correctly simply by adding a calendar field.

For users requiring non-Gregorian dates in EHR and other health systems there are two approaches.
One is to treat non-Gregorian dates as a localisation issue, to be handled inside the application and
GUI environment. The other is to actually add further sibling packages to the openEHR date/time
package, for each new calendar or calendar group required. Conversion algorithms would most likely
be needed in and out of the Gregorian types to enable interoperability of information drawn from different
applications or sources. This approach may require a substantial modelling effort.

Algorithms for conversion between the Egyptian, Armenian, Khwarizmian, Persian, Ethiopian, Coptic,
Republican, Macedonian, Syrian, Julian Roman, Gregorian, Islamic A, Islamic B, Baha'i and
Saka calendars are described by cite:[Richards1998] and are based on the work of D. A. Hatcher (1986).

==== Representation

All of the date/time classes described here are defined so as to have an attribute called value of type
String, in the form of an {iso_8601_official}[ISO 8601:2019] string, with the two above-described deviations allowed. ISO 8601 is convenient for this purpose, as it is a simple
syntax, and covers not only all four variants of fully-specified date/time described here, but also
the partial varieties. The deviations support common use cases in healthcare, without compromising the semantics. Using a single string attribute significantly simplifies persistence as well as mapping
to XML-based formalisms, which use a mostly ISO 8601 compliant date/time representation.
The ISO 8601 semantics assumed by EHR are defined in classes found in the classes
`Iso8601_date`, `Iso8601_time`, `Iso8601_date_time`, `Iso8601_duration`, from the
{openehr_foundation_types}#_time_types[`base.foundation_types.time` package]. These classes are inherited into the corresponding classes
defined below.

NOTE: it is strongly recommended that where possible, the _extended_ form of the ISO 8601 date/time syntax is used, i.e. the use of dashes in dates (e.g. `2018-03-14` rather than `20180314`) and colons for times (i.e. `14:24:00` instead of `142400`). This greatly aids human readability, and reduces the need for special date/time display rendering.

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}dv_temporal.adoc[]

include::{uml_export_dir}/classes/{pkg}dv_date.adoc[]

include::{uml_export_dir}/classes/{pkg}dv_time.adoc[]

include::{uml_export_dir}/classes/{pkg}dv_date_time.adoc[]

include::{uml_export_dir}/classes/{pkg}dv_duration.adoc[]
